/**
 * PDF Audit Report Generator
 *
 * Generates a downloadable PDF audit report for a secured anchor,
 * including document info, cryptographic proof, and lifecycle timeline.
 *
 * @see P6-TS-05
 */

import { jsPDF } from 'jspdf';

interface AuditReportData {
  publicId: string;
  filename: string;
  fingerprint: string;
  status: string;
  fileSize?: number;
  credentialType?: string;
  issuerName?: string;
  createdAt: string;
  issuedAt?: string;
  securedAt?: string;
  revokedAt?: string;
  revocationReason?: string;
  expiresAt?: string;
  networkReceipt?: string;
  blockHeight?: number;
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short',
    timeZone: 'UTC',
  }) + ' UTC';
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export function generateAuditReport(data: AuditReportData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ── Header ──────────────────────────────────────────
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Arkova Verification Certificate', margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${formatDate(new Date().toISOString())}`, margin, y);
  y += 4;
  doc.text(`Verification ID: ${data.publicId}`, margin, y);
  y += 8;

  // Separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 10;

  // ── Status ──────────────────────────────────────────
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  const statusText = data.status === 'SECURED' ? 'VERIFIED' : data.status;
  doc.text(`Status: ${statusText}`, margin, y);
  y += 12;

  // ── Section: Document Information ───────────────────
  y = addSection(doc, 'Document Information', y, margin);
  y = addField(doc, 'Filename', data.filename, y, margin, contentWidth);
  if (data.fileSize) {
    y = addField(doc, 'File Size', formatFileSize(data.fileSize), y, margin, contentWidth);
  }
  if (data.credentialType) {
    y = addField(doc, 'Credential Type', data.credentialType, y, margin, contentWidth);
  }
  y += 4;

  // ── Section: Issuer ─────────────────────────────────
  if (data.issuerName) {
    y = addSection(doc, 'Issuer', y, margin);
    y = addField(doc, 'Organization', data.issuerName, y, margin, contentWidth);
    if (data.issuedAt) {
      y = addField(doc, 'Issued', formatDate(data.issuedAt), y, margin, contentWidth);
    }
    y += 4;
  }

  // ── Section: Cryptographic Proof ────────────────────
  y = addSection(doc, 'Cryptographic Proof', y, margin);
  y = addField(doc, 'Fingerprint (SHA-256)', '', y, margin, contentWidth);
  // Fingerprint on its own line (monospace)
  doc.setFontSize(7);
  doc.setFont('courier', 'normal');
  doc.text(data.fingerprint, margin + 4, y);
  y += 6;

  if (data.networkReceipt) {
    y = addField(doc, 'Network Receipt', '', y, margin, contentWidth);
    doc.setFontSize(7);
    doc.setFont('courier', 'normal');
    doc.text(data.networkReceipt, margin + 4, y);
    y += 6;
  }

  if (data.blockHeight) {
    y = addField(doc, 'Network Record', `#${data.blockHeight.toLocaleString()}`, y, margin, contentWidth);
  }

  if (data.securedAt) {
    y = addField(doc, 'Observed Time', formatDate(data.securedAt), y, margin, contentWidth);
  }
  y += 4;

  // ── Section: Lifecycle ──────────────────────────────
  y = addSection(doc, 'Lifecycle', y, margin);
  y = addField(doc, 'Created', formatDate(data.createdAt), y, margin, contentWidth);
  if (data.securedAt) {
    y = addField(doc, 'Secured', formatDate(data.securedAt), y, margin, contentWidth);
  }
  if (data.expiresAt) {
    y = addField(doc, 'Expires', formatDate(data.expiresAt), y, margin, contentWidth);
  }
  if (data.revokedAt) {
    y = addField(doc, 'Revoked', formatDate(data.revokedAt), y, margin, contentWidth);
  }
  if (data.revocationReason) {
    y = addField(doc, 'Revocation Reason', data.revocationReason, y, margin, contentWidth);
  }
  y += 8;

  // ── Footer ──────────────────────────────────────────
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 6;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(120, 120, 120);
  doc.text(
    'This certificate was generated by Arkova. It asserts that the document fingerprint was observed at the stated time.',
    margin,
    y,
    { maxWidth: contentWidth }
  );
  y += 8;
  doc.text(
    'This certificate does NOT assert the accuracy of document contents, the identity of the issuer, or the validity of the credential itself.',
    margin,
    y,
    { maxWidth: contentWidth }
  );

  // ── Save ────────────────────────────────────────────
  const safeName = data.filename.replace(/[^a-zA-Z0-9.-]/g, '_').substring(0, 50);
  doc.save(`arkova-certificate-${safeName}.pdf`);
}

function addSection(doc: jsPDF, title: string, y: number, margin: number): number {
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(title, margin, y);
  y += 7;
  return y;
}

function addField(
  doc: jsPDF,
  label: string,
  value: string,
  y: number,
  margin: number,
  contentWidth: number,
): number {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text(label, margin + 4, y);

  if (value) {
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const labelWidth = doc.getTextWidth(label + '  ');
    doc.text(value, margin + 4 + labelWidth, y, { maxWidth: contentWidth - labelWidth - 8 });
  }

  y += 5;
  return y;
}
