#!/usr/bin/env -S npx tsx
/** Collect the start-consumable B1 pre-clock packet from live authenticated facts. */

import { constants as fsConstants } from 'node:fs';
import { open, readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { parseArgs } from 'node:util';

import {
  authorizeB1PreclockMutation,
  collectB1SchedulerPreclockArtifact,
  createB1PreclockProductionCollector,
} from './s33-b1-scheduler-preclock-production-adapter';

const MAX_INPUT_BYTES = 4 * 1024 * 1024;

export interface B1PreclockCliDependencies {
  readonly readText: (path: string) => Promise<string>;
  readonly writeExclusive: (path: string, raw: string) => Promise<void>;
  readonly readBack: (path: string) => Promise<string>;
  readonly collect: (
    admission: string,
    treasuryPlan: string,
    preparationAuthority: string,
    ctoPreparationConfirmation: string,
  ) => Promise<string>;
}

function required(value: string | undefined, option: string): string {
  if (value === undefined || value.trim().length === 0) {
    throw new Error(`RIG-B1 pre-clock generation requires --${option}.`);
  }
  return value;
}

async function readBoundedRegularFile(path: string): Promise<string> {
  const handle = await open(path, fsConstants.O_RDONLY | fsConstants.O_NOFOLLOW);
  try {
    const stat = await handle.stat();
    if (!stat.isFile() || stat.size < 1 || stat.size > MAX_INPUT_BYTES) {
      throw new Error(`RIG-B1 pre-clock input ${path} must be a non-empty bounded regular file.`);
    }
    return await handle.readFile('utf8');
  } finally {
    await handle.close();
  }
}

async function execute(
  argv: readonly string[],
  dependencies: B1PreclockCliDependencies,
): Promise<Readonly<{ status: 'PRECLOCK_ARTIFACT_WRITTEN'; output: string; bytes: number }>> {
  const { values } = parseArgs({
    args: [...argv],
    strict: true,
    allowPositionals: false,
    options: {
      admission: { type: 'string' },
      'treasury-plan': { type: 'string' },
      'preparation-authority': { type: 'string' },
      'cto-preparation-confirmation': { type: 'string' },
      output: { type: 'string' },
    },
  });
  const admissionPath = required(values.admission, 'admission');
  const treasuryPlanPath = required(values['treasury-plan'], 'treasury-plan');
  const preparationAuthorityPath = required(
    values['preparation-authority'],
    'preparation-authority',
  );
  const ctoPreparationConfirmation = required(
    values['cto-preparation-confirmation'],
    'cto-preparation-confirmation',
  );
  const output = required(values.output, 'output');
  const [admission, treasuryPlan, preparationAuthority] = await Promise.all([
    dependencies.readText(admissionPath),
    dependencies.readText(treasuryPlanPath),
    dependencies.readText(preparationAuthorityPath),
  ]);
  const raw = await dependencies.collect(
    admission,
    treasuryPlan,
    preparationAuthority,
    ctoPreparationConfirmation,
  );
  await dependencies.writeExclusive(output, raw);
  if (await dependencies.readBack(output) !== raw) {
    throw new Error('RIG-B1 pre-clock artifact readback differs from generated bytes.');
  }
  return Object.freeze({
    status: 'PRECLOCK_ARTIFACT_WRITTEN',
    output,
    bytes: Buffer.byteLength(raw),
  });
}

export function runS33B1SchedulerPreclockCli(
  argv: readonly string[],
): Promise<Readonly<{ status: 'PRECLOCK_ARTIFACT_WRITTEN'; output: string; bytes: number }>> {
  return execute(argv, {
    readText: readBoundedRegularFile,
    writeExclusive: (path, raw) => writeFile(path, raw, { encoding: 'utf8', mode: 0o600, flag: 'wx' }),
    readBack: (path) => readFile(path, 'utf8'),
    collect: (admission, treasuryPlan, preparationAuthority, confirmation) => {
      const authorization = authorizeB1PreclockMutation(
        admission,
        treasuryPlan,
        preparationAuthority,
        confirmation,
      );
      return collectB1SchedulerPreclockArtifact(
        admission,
        treasuryPlan,
        authorization,
        createB1PreclockProductionCollector(),
      );
    },
  });
}

/** Test-only seam. */
export function runS33B1SchedulerPreclockCliForTest(
  argv: readonly string[],
  dependencies: B1PreclockCliDependencies,
): Promise<Readonly<{ status: 'PRECLOCK_ARTIFACT_WRITTEN'; output: string; bytes: number }>> {
  if (process.env.NODE_ENV !== 'test') throw new Error('Injected B1 pre-clock CLI dependencies are test-only.');
  return execute(argv, dependencies);
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  runS33B1SchedulerPreclockCli(process.argv.slice(2)).then((result) => {
    process.stdout.write(`${JSON.stringify(result)}\n`);
  }).catch((error) => {
    process.stderr.write(`ERROR: RIG-B1 pre-clock generation failed: ${error instanceof Error ? error.message : 'unknown failure'}\n`);
    process.exitCode = 1;
  });
}
