/**
 * Build identity for this Worker bundle.
 *
 * GENERATED by `services/edge/scripts/generate-build-info.mjs` (invoked as
 * `npm run build:info` from `.github/workflows/deploy-edge.yml`, immediately
 * before `wrangler deploy`). Wrangler `[vars]` in `wrangler.toml` cannot
 * safely carry a per-build git SHA — a `[vars]` entry is a static TOML
 * value checked into source, not something wrangler derives at deploy
 * time — so a generated source file is the mechanism instead.
 *
 * This checked-in copy is the PLACEHOLDER used by local dev, `vitest`, and
 * any bundle built without running the generator first. `/health` (see
 * `src/index.ts`) reads `BUILD_INFO` and returns it verbatim, and
 * `scripts/ci/check-edge-deployed-version.ts` reads that field from the
 * live endpoint to detect a merged-but-undeployed edge (SCRUM-3907 /
 * SCRUM-3797 — prod `arkova-edge` was a pre-June manual `wrangler deploy`
 * with no way to tell what commit it was actually running).
 *
 * Do not hand-edit the values below outside the generator — `npm run
 * build:info` overwrites this whole file, comments included.
 */

export interface BuildInfo {
  /** Full 40-character git commit SHA the running bundle was built from, or 'local-dev' for an ungenerated/local build. */
  git_sha: string;
  /** ISO-8601 UTC timestamp of the `npm run build:info` run, or null for an ungenerated/local build. */
  built_at: string | null;
}

export const BUILD_INFO: BuildInfo = {
  git_sha: 'local-dev',
  built_at: null,
};
