/**
 * CLE Compliance-Log Export Worker (SCRUM-1870 — CLE-R2)
 *
 * Generates an auditor-ready CLE (Continuing Legal Education) compliance log for
 * an attorney over a reporting period for a specific US state jurisdiction, in
 * both PDF and JSON form, uploads each artifact to Supabase Storage, and returns
 * a short-lived signed URL for each.
 *
 * It also emits a `cle_log.exported` audit event carrying METADATA ONLY
 * (actor, jurisdiction, period, format, record count, request id) — never any
 * export body content (CC7 no-content-leak).
 *
 * Ethics hours are reported as a SEPARATE subtotal in BOTH the PDF summary and
 * the JSON `summary` block — never folded into the total credit-hours figure.
 *
 * Constitution refs:
 *   - 1.4  : never log PII; only public_id + counts. Service-role DB access.
 *   - 1.5  : timestamps in UTC; "Network Observed Time" framing for chain time.
 *   - 1.6  : worker-only — never imports client-side fingerprint code.
 *   - 1.8  : `cle_log_v1` JSON schema is additive/frozen-friendly.
 *
 * Bar framing: this log is informational. Arkova is not affiliated with any
 * state bar; compliance determination stays with the licensee/state bar. The
 * mandatory disclaimer below is rendered verbatim into the PDF and embedded in
 * the JSON document.
 *
 * Reuse: the Supabase Storage seam (`createSupabaseStorageAdapter` /
 * `CpeExportStorage`) is imported from the sibling CPE export module rather than
 * duplicated — the two exports share identical Storage upload/sign semantics.
 */
import { randomUUID } from 'node:crypto';
import { Buffer } from 'node:buffer';
import { jsPDF } from 'jspdf';
import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Logger } from '../utils/logger.js';
import {
  createSupabaseStorageAdapter,
  SIGNED_URL_TTL_SECONDS,
  type CpeExportStorage,
} from './cpe-log-export.js';
import { US_STATE_CODES } from '../compliance/professional-education.js';

// Re-export the shared Storage seam so callers (and tests) can import either
// from the CLE module or the CPE module without reaching across domains.
export { createSupabaseStorageAdapter, SIGNED_URL_TTL_SECONDS };
export type { CpeExportStorage };

/** Stable, versioned JSON export schema tag. */
export const CLE_LOG_SCHEMA_VERSION = 'cle_log_v1' as const;

/**
 * Mandatory CLE disclaimer — rendered VERBATIM into the PDF and embedded in the
 * JSON document. This is the literal SCRUM-1870 acceptance-criteria text.
 *
 * ⚠️ PO FLAG (see PR body): the AC text says "state bar **of accountancy** or
 * bar association". "of accountancy" appears to be a copy-paste artifact from
 * the CPE/NASBA disclaimer (accountancy = CPA, not CLE/attorneys); the intended
 * legal wording is almost certainly "any state bar or bar association". We
 * implement the AC text verbatim here (the test asserts it) and flag it for
 * Carson to confirm/correct before soak/merge — we do NOT silently reword legal
 * copy.
 */
export const CLE_DISCLAIMER_TEXT =
  'This log is generated by Arkova. Arkova is not affiliated with any state bar of accountancy or bar association. CLE compliance determination remains the responsibility of the licensee and their state bar.';

/** Default Storage bucket for generated exports (overridable via deps/env). */
const DEFAULT_EXPORTS_BUCKET = process.env.EXPORTS_STORAGE_BUCKET || 'exports';

/** Cap records per export to keep generation bounded (perf + memory). Mirrors CPE. */
const MAX_EXPORT_RECORDS = 5000;

const STATE_CODE_SET: ReadonlySet<string> = new Set<string>(US_STATE_CODES);

/**
 * Normalize a caller-supplied jurisdiction to a bare US state code.
 * Accepts a bare code (`CA`, `ca`) or the ISO-3166-2 prefixed form (`US-CA`).
 * Returns the canonical upper-case state code, or null when unrecognised.
 */
export function normalizeJurisdiction(input: unknown): string | null {
  if (typeof input !== 'string') return null;
  let code = input.trim().toUpperCase();
  if (code.startsWith('US-')) code = code.slice(3);
  return STATE_CODE_SET.has(code) ? code : null;
}

// ─── Anchor row shape (worker query projection) ──────
export interface CleExportAnchorRow {
  id: string;
  public_id: string | null;
  org_id: string | null;
  user_id: string | null;
  label: string | null;
  filename: string | null;
  status: string;
  issued_at: string | null;
  chain_timestamp: string | null;
  created_at: string;
  credential_type: string | null;
  metadata: Record<string, unknown> | null;
  cle_metadata: Record<string, unknown> | null;
}

// ─── cle_log_v1 schema (frozen / additive-friendly) ──
/**
 * Per-credential record. Every field is nullable so a partially-extracted
 * anchor still exports cleanly. `extraction_confidence` / `extraction_source`
 * are DELIBERATELY ABSENT — they are internal-only signals, never exported.
 * `ethics_hours` is a SEPARATE field from `credit_hours` (the total) — they are
 * never combined.
 */
export const CleLogRecordSchema = z
  .object({
    public_id: z.string().nullable(),
    title: z.string().nullable(),
    provider: z.string().nullable(),
    provider_approval_status: z.string().nullable(),
    credit_hours: z.number().nullable(),
    ethics_hours: z.number().nullable(),
    jurisdiction: z.string().nullable(),
    delivery_format: z.string().nullable(),
    completion_date: z.string().nullable(),
    verification_url: z.string().nullable(),
    anchor_timestamp: z.string().nullable(),
    evidence_level: z.string().nullable(),
    status: z.string(),
  })
  .strict();

export type CleLogRecord = z.infer<typeof CleLogRecordSchema>;

/**
 * Aggregate summary. `ethics_hours` is a distinct subtotal alongside the total
 * `total_credit_hours` — the AC requires the ethics figure to be shown
 * separately and never merged into the total.
 */
export const CleLogSummarySchema = z
  .object({
    total_credit_hours: z.number(),
    ethics_hours: z.number(),
    approved_provider_hours: z.number(),
    unverified_provider_hours: z.number(),
    hours_by_delivery_format: z.record(z.string(), z.number()),
  })
  .strict();

export type CleLogSummary = z.infer<typeof CleLogSummarySchema>;

export const CleLogV1Schema = z
  .object({
    schema: z.literal(CLE_LOG_SCHEMA_VERSION),
    generated_at: z.string(),
    jurisdiction: z.string(),
    period: z.object({ start: z.string(), end: z.string() }).strict(),
    record_count: z.number().int().nonnegative(),
    summary: CleLogSummarySchema,
    records: z.array(CleLogRecordSchema),
    disclaimer: z.literal(CLE_DISCLAIMER_TEXT),
  })
  .strict();

export type CleLogV1Document = z.infer<typeof CleLogV1Schema>;

export interface CleLogExportDeps {
  db: SupabaseClient;
  storage: CpeExportStorage;
  logger: Pick<Logger, 'info' | 'warn' | 'error'>;
  /** Public app base URL for building per-credential verification links. */
  frontendUrl: string;
  /** Storage bucket override (defaults to EXPORTS_STORAGE_BUCKET or `exports`). */
  bucket?: string;
}

export interface CleLogExportArgs {
  userId: string;
  orgId: string;
  /** US state code (bare `CA` or `US-CA`); validated/normalized in-worker. */
  jurisdiction: string;
  periodStart: string; // YYYY-MM-DD (inclusive)
  periodEnd: string; // YYYY-MM-DD (inclusive)
  requestId?: string;
}

export interface CleLogExportArtifact {
  signed_url: string;
  path: string;
  expires_in: number;
}

export interface CleLogExportResult {
  request_id: string;
  record_count: number;
  jurisdiction: string;
  disclaimer: string;
  exports: {
    pdf: CleLogExportArtifact;
    json: CleLogExportArtifact;
  };
}

// ─── Field mapping helpers ───────────────────────────
function asString(value: unknown): string | null {
  return typeof value === 'string' && value.trim() ? value.trim() : null;
}

function asNumber(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.trim() !== '') {
    const n = Number(value);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

/** Reduce an ISO date-time / date string to YYYY-MM-DD (or null). */
function asDateOnly(value: unknown): string | null {
  const s = asString(value);
  if (!s) return null;
  const dateOnly = s.slice(0, 10);
  return /^\d{4}-\d{2}-\d{2}$/.test(dateOnly) ? dateOnly : null;
}

/**
 * Map a single anchor row to a public-safe CLE log record.
 *
 * Field sources (per SCRUM-1870 AC; canonical `cle_metadata` shape is
 * `CleMetadataSchema` in compliance/professional-education.ts):
 *   title                    ← cle_metadata.course_title → label → filename
 *   provider                 ← cle_metadata.approved_provider_name
 *   provider_approval_status ← cle_metadata.provider_approval_status
 *   credit_hours (total)     ← cle_metadata.credit_hours
 *   ethics_hours (SEPARATE)  ← cle_metadata.ethics_hours
 *   jurisdiction             ← cle_metadata.jurisdiction (US state code)
 *   delivery_format          ← cle_metadata.delivery_format
 *   completion_date          ← issued_at (fallback metadata.credential_issued_at)
 *   verification_url         ← `${frontendUrl}/verify/${public_id}`
 *   anchor_timestamp         ← chain_timestamp (Network Observed Time)
 *   evidence_level           ← metadata.verification_level
 *
 * extraction_confidence / extraction_source are intentionally NOT mapped
 * (allowlist mapper — internal-only signals never leave the worker).
 */
export function buildCleLogRecord(
  anchor: CleExportAnchorRow,
  frontendUrl: string,
): CleLogRecord {
  const meta = (anchor.metadata ?? {}) as Record<string, unknown>;
  const cle = (anchor.cle_metadata ?? {}) as Record<string, unknown>;

  const title =
    asString(cle.course_title) ?? asString(anchor.label) ?? asString(anchor.filename);
  const completion = asDateOnly(anchor.issued_at) ?? asDateOnly(meta.credential_issued_at);
  const verificationUrl = anchor.public_id
    ? `${frontendUrl.replace(/\/+$/, '')}/verify/${anchor.public_id}`
    : null;

  return {
    public_id: anchor.public_id,
    title,
    provider: asString(cle.approved_provider_name),
    provider_approval_status: asString(cle.provider_approval_status),
    credit_hours: asNumber(cle.credit_hours),
    ethics_hours: asNumber(cle.ethics_hours),
    jurisdiction: asString(cle.jurisdiction),
    delivery_format: asString(cle.delivery_format),
    completion_date: completion,
    verification_url: verificationUrl,
    anchor_timestamp: anchor.chain_timestamp,
    evidence_level: asString(meta.verification_level),
    status: anchor.status,
  };
}

/**
 * Compute the aggregate summary. Ethics hours are accumulated into their own
 * subtotal — never added to `total_credit_hours`. Provider hours split on
 * `provider_approval_status === 'approved'`; everything else (not_approved /
 * unknown / null) is "unverified". Delivery-format buckets sum credit hours.
 */
export function computeCleSummary(records: CleLogRecord[]): CleLogSummary {
  let totalCreditHours = 0;
  let ethicsHours = 0;
  let approvedProviderHours = 0;
  let unverifiedProviderHours = 0;
  const hoursByDeliveryFormat: Record<string, number> = {};

  for (const r of records) {
    const credit = r.credit_hours ?? 0;
    const ethics = r.ethics_hours ?? 0;
    totalCreditHours += credit;
    ethicsHours += ethics;

    if (r.provider_approval_status === 'approved') {
      approvedProviderHours += credit;
    } else {
      unverifiedProviderHours += credit;
    }

    if (r.delivery_format) {
      hoursByDeliveryFormat[r.delivery_format] =
        (hoursByDeliveryFormat[r.delivery_format] ?? 0) + credit;
    }
  }

  return {
    total_credit_hours: totalCreditHours,
    ethics_hours: ethicsHours,
    approved_provider_hours: approvedProviderHours,
    unverified_provider_hours: unverifiedProviderHours,
    hours_by_delivery_format: hoursByDeliveryFormat,
  };
}

// ─── PDF rendering ───────────────────────────────────
function formatUtc(value: string | null): string {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return value;
  return (
    d.toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }) + ' UTC'
  );
}

function generateCleLogPdf(
  records: CleLogRecord[],
  summary: CleLogSummary,
  jurisdiction: string,
  periodStart: string,
  periodEnd: string,
): Buffer {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ── Title ──
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Arkova CLE Compliance Log', margin, y);
  y += 9;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${formatUtc(new Date().toISOString())}`, margin, y);
  y += 4;
  doc.text(`Jurisdiction: ${jurisdiction}`, margin, y);
  y += 4;
  doc.text(`Reporting Period: ${periodStart} to ${periodEnd}`, margin, y);
  y += 4;
  doc.text(`Records: ${records.length}`, margin, y);
  y += 8;

  // ── Summary (ethics hours shown as a SEPARATE subtotal) ──
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', margin, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);
  doc.text(`Total CLE Credit Hours: ${summary.total_credit_hours}`, margin, y);
  y += 4;
  // Ethics is a distinct line item, never merged into the total above.
  doc.text(`Ethics Hours (subtotal): ${summary.ethics_hours}`, margin, y);
  y += 4;
  doc.text(
    `Approved Provider Hours: ${summary.approved_provider_hours}   |   Unverified Provider Hours: ${summary.unverified_provider_hours}`,
    margin,
    y,
  );
  y += 4;
  const byFormat = Object.entries(summary.hours_by_delivery_format);
  if (byFormat.length > 0) {
    const formatLine = byFormat.map(([fmt, hrs]) => `${fmt}: ${hrs}`).join('   |   ');
    const formatLines = doc.splitTextToSize(`Hours by Delivery Format — ${formatLine}`, contentWidth);
    doc.text(formatLines, margin, y);
    y += formatLines.length * 4;
  }
  y += 4;

  // ── Mandatory CLE disclaimer (verbatim) ──
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 6;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(90, 90, 90);
  const disclaimerLines = doc.splitTextToSize(CLE_DISCLAIMER_TEXT, contentWidth);
  doc.text(disclaimerLines, margin, y);
  y += disclaimerLines.length * 4 + 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 8;

  // ── Records ──
  doc.setTextColor(0, 0, 0);
  for (const r of records) {
    if (y > 255) {
      doc.addPage();
      y = margin;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(r.title ?? '(untitled)', margin, y, { maxWidth: contentWidth });
    y += 5;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(70, 70, 70);
    const line1 = [
      `Provider: ${r.provider ?? '—'}`,
      `Approval: ${r.provider_approval_status ?? '—'}`,
      `Jurisdiction: ${r.jurisdiction ?? '—'}`,
    ].join('   |   ');
    doc.text(line1, margin, y, { maxWidth: contentWidth });
    y += 4;
    // Credit hours and ethics hours rendered as two separate values.
    const line2 = [
      `Credit Hours: ${r.credit_hours ?? '—'}`,
      `Ethics Hours: ${r.ethics_hours ?? '—'}`,
      `Delivery: ${r.delivery_format ?? '—'}`,
    ].join('   |   ');
    doc.text(line2, margin, y, { maxWidth: contentWidth });
    y += 4;
    const line3 = [
      `Completion: ${r.completion_date ?? '—'}`,
      `Evidence Level: ${r.evidence_level ?? '—'}`,
      `Network Observed Time: ${formatUtc(r.anchor_timestamp)}`,
    ].join('   |   ');
    doc.text(line3, margin, y, { maxWidth: contentWidth });
    y += 4;
    if (r.verification_url) {
      doc.setTextColor(40, 90, 160);
      doc.text(`Verify: ${r.verification_url}`, margin, y, { maxWidth: contentWidth });
      doc.setTextColor(70, 70, 70);
      y += 4;
    }
    y += 3;
  }

  return Buffer.from(doc.output('arraybuffer'));
}

// ─── Audit event (METADATA ONLY — CC7) ───────────────
async function emitCleLogExportedAudit(
  deps: CleLogExportDeps,
  args: {
    userId: string;
    orgId: string;
    jurisdiction: string;
    periodStart: string;
    periodEnd: string;
    recordCount: number;
    requestId: string;
  },
): Promise<void> {
  // Only the allowed metadata keys. No titles, providers, public_ids, URLs,
  // or any per-credential content — verified by the CC7 leak test.
  const details = {
    jurisdiction: args.jurisdiction,
    period_start: args.periodStart,
    period_end: args.periodEnd,
    format: 'pdf+json',
    record_count: args.recordCount,
    request_id: args.requestId,
  };

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any, arkova/missing-org-filter -- audit insert writes a new event row; org_id + actor_id are set on the row (not a tenant-leaking read).
    const result = await (deps.db.from('audit_events') as any).insert({
      event_type: 'cle_log.exported',
      event_category: 'ADMIN',
      actor_id: args.userId,
      org_id: args.orgId,
      target_type: 'cle_log_export',
      details: JSON.stringify(details),
    });
    if (result?.error) {
      // Audit failure is non-fatal — the export still succeeded. Log coarse
      // context only (no PII), consistent with worker job conventions.
      deps.logger.warn(
        { orgId: args.orgId, requestId: args.requestId, code: result.error.code },
        'cle_log.exported audit insert failed (non-fatal)',
      );
    }
  } catch (err) {
    deps.logger.warn(
      { requestId: args.requestId, error: err instanceof Error ? err.message : 'unknown' },
      'cle_log.exported audit insert threw (non-fatal)',
    );
  }
}

// ─── Orchestration ───────────────────────────────────
/**
 * Generate the CLE compliance log for one user over a period for a specific US
 * state jurisdiction, in both PDF and JSON, upload to Storage, and return signed
 * URLs + a metadata-only audit.
 *
 * Org/user scope: the query is filtered by BOTH `user_id` and `org_id` so a
 * caller can only ever export their own anchors within their org. The endpoint
 * additionally rejects cross-user requests before reaching here (defense in
 * depth). The jurisdiction filter matches `cle_metadata->>'jurisdiction'` to the
 * requested (normalized) state code.
 */
export async function generateCleLogExport(
  args: CleLogExportArgs,
  deps: CleLogExportDeps,
): Promise<CleLogExportResult> {
  const requestId = args.requestId ?? randomUUID();
  const bucket = deps.bucket ?? DEFAULT_EXPORTS_BUCKET;

  const jurisdiction = normalizeJurisdiction(args.jurisdiction);
  if (!jurisdiction) {
    throw new Error(`invalid jurisdiction for CLE export: ${String(args.jurisdiction)}`);
  }

  // 1. Fetch the caller's CLE anchors in the reporting period for the requested
  //    jurisdiction. Service-role client; scope is enforced by the explicit
  //    user_id + org_id filters. `issued_at` is the credential completion date
  //    used for the period window; rows without issued_at are excluded.
  //    The jurisdiction filter matches the bare state code OR the `US-`prefixed
  //    form stored in `cle_metadata->>'jurisdiction'`.
  const { data, error } = await deps.db
    .from('anchors')
    .select(
      'id, public_id, org_id, user_id, label, filename, status, issued_at, chain_timestamp, created_at, credential_type, metadata, cle_metadata',
    )
    .eq('user_id', args.userId)
    .eq('org_id', args.orgId)
    .eq('credential_type', 'CLE')
    .is('deleted_at', null)
    .or(`cle_metadata->>jurisdiction.eq.${jurisdiction},cle_metadata->>jurisdiction.eq.US-${jurisdiction}`)
    .gte('issued_at', `${args.periodStart}T00:00:00.000Z`)
    .lte('issued_at', `${args.periodEnd}T23:59:59.999Z`)
    .order('issued_at', { ascending: true })
    .limit(MAX_EXPORT_RECORDS);

  if (error) {
    throw new Error(`failed to load CLE anchors for export: ${error.message}`);
  }

  const anchors = ((data ?? []) as CleExportAnchorRow[]).slice(0, MAX_EXPORT_RECORDS);
  const records = anchors.map((a) => buildCleLogRecord(a, deps.frontendUrl));
  const recordCount = records.length;
  const summary = computeCleSummary(records);

  // 2. Build artifacts.
  const jsonDoc: CleLogV1Document = {
    schema: CLE_LOG_SCHEMA_VERSION,
    generated_at: new Date().toISOString(),
    jurisdiction,
    period: { start: args.periodStart, end: args.periodEnd },
    record_count: recordCount,
    summary,
    records,
    disclaimer: CLE_DISCLAIMER_TEXT,
  };
  // Validate our own output against the frozen schema before shipping it.
  const jsonBody = JSON.stringify(CleLogV1Schema.parse(jsonDoc), null, 2);
  const pdfBody = generateCleLogPdf(records, summary, jurisdiction, args.periodStart, args.periodEnd);

  // 3. Upload both to Storage under an org/user-scoped, unguessable path.
  const base = `cle-log/${args.orgId}/${args.userId}/${requestId}`;
  const pdfPath = `${base}.pdf`;
  const jsonPath = `${base}.json`;

  const pdfUpload = await deps.storage.upload(bucket, pdfPath, new Uint8Array(pdfBody), 'application/pdf');
  if (pdfUpload.error) {
    throw new Error(`failed to upload CLE log PDF: ${pdfUpload.error.message}`);
  }
  const jsonUpload = await deps.storage.upload(bucket, jsonPath, jsonBody, 'application/json');
  if (jsonUpload.error) {
    throw new Error(`failed to upload CLE log JSON: ${jsonUpload.error.message}`);
  }

  // 4. Sign both.
  const pdfSigned = await deps.storage.createSignedUrl(bucket, pdfPath, SIGNED_URL_TTL_SECONDS);
  if (pdfSigned.error || !pdfSigned.signedUrl) {
    throw new Error(`failed to sign CLE log PDF URL: ${pdfSigned.error?.message ?? 'no url'}`);
  }
  const jsonSigned = await deps.storage.createSignedUrl(bucket, jsonPath, SIGNED_URL_TTL_SECONDS);
  if (jsonSigned.error || !jsonSigned.signedUrl) {
    throw new Error(`failed to sign CLE log JSON URL: ${jsonSigned.error?.message ?? 'no url'}`);
  }

  // 5. Audit (metadata only — non-fatal).
  await emitCleLogExportedAudit(deps, {
    userId: args.userId,
    orgId: args.orgId,
    jurisdiction,
    periodStart: args.periodStart,
    periodEnd: args.periodEnd,
    recordCount,
    requestId,
  });

  deps.logger.info(
    { requestId, orgId: args.orgId, jurisdiction, recordCount },
    'CLE compliance log exported',
  );

  return {
    request_id: requestId,
    record_count: recordCount,
    jurisdiction,
    disclaimer: CLE_DISCLAIMER_TEXT,
    exports: {
      pdf: { signed_url: pdfSigned.signedUrl, path: pdfPath, expires_in: SIGNED_URL_TTL_SECONDS },
      json: { signed_url: jsonSigned.signedUrl, path: jsonPath, expires_in: SIGNED_URL_TTL_SECONDS },
    },
  };
}
