/**
 * CPE Compliance-Log Export Worker (SCRUM-1860 / SCRUM-1848 — CPE-R2)
 *
 * Generates an auditor-ready CPE (Continuing Professional Education) compliance
 * log for a CPA over a reporting period, in both PDF and JSON form, uploads each
 * artifact to Supabase Storage, and returns a short-lived signed URL for each.
 *
 * It also emits a `cpe_log.exported` audit event carrying METADATA ONLY
 * (actor, period, format, record count, request id) — never any export body
 * content (CC7 no-content-leak).
 *
 * Constitution refs:
 *   - 1.4  : never log PII; only public_id + counts. Service-role DB access.
 *   - 1.5  : timestamps in UTC; "Network Observed Time" framing for chain time.
 *   - 1.6  : worker-only — never imports client-side fingerprint code.
 *   - 1.8  : `cpe_log_v1` JSON schema is additive/frozen-friendly.
 *
 * NASBA framing: this log is informational. Arkova is not affiliated with NASBA
 * or any state board; compliance determination stays with the licensee/board.
 * The mandatory disclaimer below is rendered verbatim into the PDF and embedded
 * in the JSON document.
 */
import { randomUUID } from 'node:crypto';
import { Buffer } from 'node:buffer';
import { jsPDF } from 'jspdf';
import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Logger } from '../utils/logger.js';
import { asString, asNumber, asDateOnly, stripTrailingSlashes, formatUtc } from './export-format-helpers.js';

/** Stable, versioned JSON export schema tag. */
export const CPE_LOG_SCHEMA_VERSION = 'cpe_log_v1' as const;

/**
 * Mandatory NASBA disclaimer — rendered VERBATIM into the PDF and embedded in
 * the JSON document. Do not reword; auditors and the state board rely on this
 * exact non-affiliation statement.
 */
export const NASBA_DISCLAIMER_TEXT =
  'This log is generated by Arkova. Arkova is not affiliated with NASBA or any state board of accountancy. CPE compliance determination remains the responsibility of the licensee and their state board.';

/** Default Storage bucket for generated exports (overridable via deps/env). */
const DEFAULT_EXPORTS_BUCKET = process.env.EXPORTS_STORAGE_BUCKET || 'exports';

/** Signed-URL lifetime: 1 hour. Matches the per-user export cadence. */
export const SIGNED_URL_TTL_SECONDS = 3600;

/** Cap records per export to keep generation bounded (perf + memory). */
const MAX_EXPORT_RECORDS = 5000;

// ─── Anchor row shape (worker query projection) ──────
export interface CpeExportAnchorRow {
  id: string;
  public_id: string | null;
  org_id: string | null;
  user_id: string | null;
  label: string | null;
  filename: string | null;
  status: string;
  issued_at: string | null;
  chain_timestamp: string | null;
  created_at: string;
  credential_type: string | null;
  metadata: Record<string, unknown> | null;
  cpe_metadata: Record<string, unknown> | null;
}

// ─── cpe_log_v1 schema (frozen / additive-friendly) ──
/**
 * Per-credential record. Every field is nullable so a partially-extracted
 * anchor still exports cleanly. `extraction_confidence` / `extraction_source`
 * are DELIBERATELY ABSENT — they are internal-only signals, never exported.
 */
export const CpeLogRecordSchema = z
  .object({
    public_id: z.string().nullable(),
    title: z.string().nullable(),
    provider: z.string().nullable(),
    nasba_status: z.string().nullable(),
    cpe_hours: z.number().nullable(),
    field_of_study: z.string().nullable(),
    delivery_method: z.string().nullable(),
    completion_date: z.string().nullable(),
    verification_url: z.string().nullable(),
    anchor_timestamp: z.string().nullable(),
    evidence_level: z.string().nullable(),
    status: z.string(),
  })
  .strict();

export type CpeLogRecord = z.infer<typeof CpeLogRecordSchema>;

export const CpeLogV1Schema = z
  .object({
    schema: z.literal(CPE_LOG_SCHEMA_VERSION),
    generated_at: z.string(),
    period: z.object({ start: z.string(), end: z.string() }).strict(),
    record_count: z.number().int().nonnegative(),
    records: z.array(CpeLogRecordSchema),
    disclaimer: z.literal(NASBA_DISCLAIMER_TEXT),
  })
  .strict();

export type CpeLogV1Document = z.infer<typeof CpeLogV1Schema>;

// ─── Storage adapter (DI — no Storage migration required) ──
/**
 * Thin Storage seam so the worker can be unit-tested without a live Supabase
 * Storage bucket, and so the bucket can be provisioned as an ops step rather
 * than a DB migration (keeps this change T2, not T3).
 */
export interface CpeExportStorage {
  upload(
    bucket: string,
    path: string,
    body: Uint8Array | string,
    contentType?: string,
  ): Promise<{ error: Error | null }>;
  createSignedUrl(
    bucket: string,
    path: string,
    expiresIn: number,
  ): Promise<{ signedUrl: string | null; error: Error | null }>;
  /**
   * Inspect a bucket's existence + visibility. Returns `exists: false` when the
   * bucket is absent so the fail-loud guard can raise a clear error instead of
   * a confusing downstream upload 500, and `isPublic` so a misconfigured PUBLIC
   * bucket — which would expose unsigned export bodies (CC7) — is rejected too.
   */
  getBucket(
    bucket: string,
  ): Promise<{ exists: boolean; isPublic: boolean | null; error: Error | null }>;
}

/** Default Storage adapter backed by the Supabase service-role client. */
export function createSupabaseStorageAdapter(db: SupabaseClient): CpeExportStorage {
  // The generated DB types don't model the Storage API; narrow locally.
  const storage = (db as unknown as { storage: {
    from(bucket: string): {
      upload(path: string, body: Uint8Array | string, opts: { contentType?: string; upsert?: boolean }):
        Promise<{ error: Error | null }>;
      createSignedUrl(path: string, expiresIn: number):
        Promise<{ data: { signedUrl: string } | null; error: Error | null }>;
    };
    getBucket(bucket: string):
      Promise<{ data: { public: boolean } | null; error: Error | null }>;
  } }).storage;

  return {
    async upload(bucket, path, body, contentType) {
      const { error } = await storage
        .from(bucket)
        .upload(path, body, { contentType, upsert: true });
      return { error };
    },
    async createSignedUrl(bucket, path, expiresIn) {
      const { data, error } = await storage.from(bucket).createSignedUrl(path, expiresIn);
      return { signedUrl: data?.signedUrl ?? null, error };
    },
    async getBucket(bucket) {
      const { data, error } = await storage.getBucket(bucket);
      // A missing bucket comes back as `data: null` (often with a "not found"
      // error). Surface existence + visibility; the caller's guard decides.
      return { exists: data != null, isPublic: data?.public ?? null, error };
    },
  };
}

/**
 * Fail-loud precondition: the exports bucket MUST exist and MUST be private.
 *
 * Provisioning the bucket is an ops step (see agents.md) — this guard does NOT
 * create it. It exists so a missing bucket fails with a clear, actionable error
 * (rather than a confusing upload 500 deeper in the flow), and so a bucket that
 * was accidentally made PUBLIC is rejected before any export body is written —
 * a public bucket would expose unsigned export contents and break the CC7
 * no-content-leak guarantee.
 */
export async function assertExportsBucketReady(
  storage: CpeExportStorage,
  bucket: string,
): Promise<void> {
  const { exists, isPublic, error } = await storage.getBucket(bucket);
  if (error && !exists) {
    throw new Error(
      `exports Storage bucket "${bucket}" is unavailable (provision it as a private bucket): ${error.message}`,
    );
  }
  if (!exists) {
    throw new Error(
      `exports Storage bucket "${bucket}" does not exist — provision it as a private bucket before exporting`,
    );
  }
  if (isPublic) {
    throw new Error(
      `exports Storage bucket "${bucket}" is PUBLIC — exports must use a private bucket so signed URLs are the only access path`,
    );
  }
}

export interface CpeLogExportDeps {
  db: SupabaseClient;
  storage: CpeExportStorage;
  logger: Pick<Logger, 'info' | 'warn' | 'error'>;
  /** Public app base URL for building per-credential verification links. */
  frontendUrl: string;
  /** Storage bucket override (defaults to EXPORTS_STORAGE_BUCKET or `exports`). */
  bucket?: string;
}

export interface CpeLogExportArgs {
  userId: string;
  orgId: string;
  periodStart: string; // YYYY-MM-DD (inclusive)
  periodEnd: string; // YYYY-MM-DD (inclusive)
  requestId?: string;
}

export interface CpeLogExportArtifact {
  signed_url: string;
  path: string;
  expires_in: number;
}

export interface CpeLogExportResult {
  request_id: string;
  record_count: number;
  disclaimer: string;
  exports: {
    pdf: CpeLogExportArtifact;
    json: CpeLogExportArtifact;
  };
}

// ─── Field mapping helpers ───────────────────────────
// asString / asNumber / asDateOnly / stripTrailingSlashes / formatUtc are
// shared with the CLE exporter and live in ./export-format-helpers.ts.

/**
 * Map a single anchor row to a public-safe CPE log record.
 *
 * Field sources (per SCRUM-1848 AC):
 *   title           ← metadata.credential_title → label → filename
 *   provider        ← cpe_metadata.sponsor_id is an ID, not a name; the human
 *                     provider name lives in metadata.credential_issuer /
 *                     source_provider
 *   nasba_status    ← cpe_metadata.nasba_status
 *   cpe_hours       ← cpe_metadata.credit_hours
 *   field_of_study  ← cpe_metadata.field_of_study
 *   delivery_method ← cpe_metadata.delivery_method
 *   completion_date ← issued_at (fallback metadata.credential_issued_at)
 *   verification_url← `${frontendUrl}/verify/${public_id}`
 *   anchor_timestamp← chain_timestamp (Network Observed Time)
 *   evidence_level  ← metadata.verification_level
 *
 * extraction_confidence / extraction_source are intentionally NOT mapped.
 */
export function buildCpeLogRecord(
  anchor: CpeExportAnchorRow,
  frontendUrl: string,
): CpeLogRecord {
  const meta = (anchor.metadata ?? {}) as Record<string, unknown>;
  const cpe = (anchor.cpe_metadata ?? {}) as Record<string, unknown>;

  const title =
    asString(meta.credential_title) ?? asString(anchor.label) ?? asString(anchor.filename);
  const provider = asString(meta.credential_issuer) ?? asString(meta.source_provider);
  const completion = asDateOnly(anchor.issued_at) ?? asDateOnly(meta.credential_issued_at);
  const verificationUrl = anchor.public_id
    ? `${stripTrailingSlashes(frontendUrl)}/verify/${anchor.public_id}`
    : null;

  return {
    public_id: anchor.public_id,
    title,
    provider,
    nasba_status: asString(cpe.nasba_status),
    cpe_hours: asNumber(cpe.credit_hours),
    field_of_study: asString(cpe.field_of_study),
    delivery_method: asString(cpe.delivery_method),
    completion_date: completion,
    verification_url: verificationUrl,
    anchor_timestamp: anchor.chain_timestamp,
    evidence_level: asString(meta.verification_level),
    status: anchor.status,
  };
}

// ─── PDF rendering ───────────────────────────────────
function generateCpeLogPdf(
  records: CpeLogRecord[],
  periodStart: string,
  periodEnd: string,
): Buffer {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ── Title ──
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Arkova CPE Compliance Log', margin, y);
  y += 9;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${formatUtc(new Date().toISOString())}`, margin, y);
  y += 4;
  doc.text(`Reporting Period: ${periodStart} to ${periodEnd}`, margin, y);
  y += 4;
  doc.text(`Records: ${records.length}`, margin, y);
  y += 8;

  // ── Mandatory NASBA disclaimer (verbatim) ──
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 6;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(90, 90, 90);
  const disclaimerLines = doc.splitTextToSize(NASBA_DISCLAIMER_TEXT, contentWidth);
  doc.text(disclaimerLines, margin, y);
  y += disclaimerLines.length * 4 + 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 8;

  // ── Records ──
  doc.setTextColor(0, 0, 0);
  for (const r of records) {
    if (y > 255) {
      doc.addPage();
      y = margin;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    // Wrap the title explicitly and advance y by the rendered line count, so a
    // long multi-line title does not overlap the Provider line below (mirrors
    // how the disclaimer is rendered). `maxWidth` alone wraps the glyphs but
    // does not tell us how many lines were drawn.
    const titleLines: string[] = doc.splitTextToSize(r.title ?? '(untitled)', contentWidth);
    const TITLE_LINE_HEIGHT = 5;
    doc.text(titleLines, margin, y);
    y += titleLines.length * TITLE_LINE_HEIGHT;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(70, 70, 70);
    const line1 = [
      `Provider: ${r.provider ?? '—'}`,
      `NASBA Status: ${r.nasba_status ?? '—'}`,
      `CPE Hours: ${r.cpe_hours ?? '—'}`,
    ].join('   |   ');
    doc.text(line1, margin, y, { maxWidth: contentWidth });
    y += 4;
    const line2 = [
      `Field of Study: ${r.field_of_study ?? '—'}`,
      `Delivery: ${r.delivery_method ?? '—'}`,
      `Evidence Level: ${r.evidence_level ?? '—'}`,
    ].join('   |   ');
    doc.text(line2, margin, y, { maxWidth: contentWidth });
    y += 4;
    const line3 = [
      `Completion: ${r.completion_date ?? '—'}`,
      `Network Observed Time: ${formatUtc(r.anchor_timestamp)}`,
    ].join('   |   ');
    doc.text(line3, margin, y, { maxWidth: contentWidth });
    y += 4;
    if (r.verification_url) {
      doc.setTextColor(40, 90, 160);
      doc.text(`Verify: ${r.verification_url}`, margin, y, { maxWidth: contentWidth });
      doc.setTextColor(70, 70, 70);
      y += 4;
    }
    y += 3;
  }

  return Buffer.from(doc.output('arraybuffer'));
}

// ─── Audit event (METADATA ONLY — CC7) ───────────────
async function emitCpeLogExportedAudit(
  deps: CpeLogExportDeps,
  args: { userId: string; orgId: string; periodStart: string; periodEnd: string; recordCount: number; requestId: string },
): Promise<void> {
  // Only the allowed metadata keys. No titles, providers, public_ids, URLs,
  // or any per-credential content — verified by the CC7 leak test.
  const details = {
    period_start: args.periodStart,
    period_end: args.periodEnd,
    format: 'pdf+json',
    record_count: args.recordCount,
    request_id: args.requestId,
  };

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any, arkova/missing-org-filter -- audit insert writes a new event row; org_id + actor_id are set on the row (not a tenant-leaking read).
    const result = await (deps.db.from('audit_events') as any).insert({
      event_type: 'cpe_log.exported',
      event_category: 'ADMIN',
      actor_id: args.userId,
      org_id: args.orgId,
      target_type: 'cpe_log_export',
      details: JSON.stringify(details),
    });
    if (result?.error) {
      // Audit failure is non-fatal — the export still succeeded. Log coarse
      // context only (no PII), consistent with worker job conventions.
      deps.logger.warn(
        { orgId: args.orgId, requestId: args.requestId, code: result.error.code },
        'cpe_log.exported audit insert failed (non-fatal)',
      );
    }
  } catch (err) {
    deps.logger.warn(
      { requestId: args.requestId, error: err instanceof Error ? err.message : 'unknown' },
      'cpe_log.exported audit insert threw (non-fatal)',
    );
  }
}

// ─── Orchestration ───────────────────────────────────
/**
 * Generate the CPE compliance log for one user over a period, in both PDF and
 * JSON, upload to Storage, and return signed URLs + a metadata-only audit.
 *
 * Org/user scope: the query is filtered by BOTH `user_id` and `org_id` so a
 * caller can only ever export their own anchors within their org. The endpoint
 * additionally rejects cross-user requests before reaching here (defense in
 * depth).
 */
export async function generateCpeLogExport(
  args: CpeLogExportArgs,
  deps: CpeLogExportDeps,
): Promise<CpeLogExportResult> {
  const requestId = args.requestId ?? randomUUID();
  const bucket = deps.bucket ?? DEFAULT_EXPORTS_BUCKET;

  // 0. Fail loud if the destination bucket is missing or public BEFORE we do any
  //    work — a missing/public bucket is an ops misconfiguration, not a per-user
  //    error, and must not silently 500 mid-upload or leak unsigned bodies.
  await assertExportsBucketReady(deps.storage, bucket);

  // 1. Fetch the caller's CPE anchors in the reporting period. Service-role
  //    client; scope is enforced by the explicit user_id + org_id filters.
  //    `issued_at` is the credential completion date used for the period
  //    window; rows without issued_at are excluded from the period view.
  const { data, error } = await deps.db
    .from('anchors')
    .select(
      'id, public_id, org_id, user_id, label, filename, status, issued_at, chain_timestamp, created_at, credential_type, metadata, cpe_metadata',
    )
    .eq('user_id', args.userId)
    .eq('org_id', args.orgId)
    .eq('credential_type', 'CPE')
    .is('deleted_at', null)
    .gte('issued_at', `${args.periodStart}T00:00:00.000Z`)
    .lte('issued_at', `${args.periodEnd}T23:59:59.999Z`)
    .order('issued_at', { ascending: true })
    .limit(MAX_EXPORT_RECORDS);

  if (error) {
    throw new Error(`failed to load CPE anchors for export: ${error.message}`);
  }

  const anchors = ((data ?? []) as CpeExportAnchorRow[]).slice(0, MAX_EXPORT_RECORDS);
  const records = anchors.map((a) => buildCpeLogRecord(a, deps.frontendUrl));
  const recordCount = records.length;

  // 2. Build artifacts.
  const jsonDoc: CpeLogV1Document = {
    schema: CPE_LOG_SCHEMA_VERSION,
    generated_at: new Date().toISOString(),
    period: { start: args.periodStart, end: args.periodEnd },
    record_count: recordCount,
    records,
    disclaimer: NASBA_DISCLAIMER_TEXT,
  };
  // Validate our own output against the frozen schema before shipping it.
  const jsonBody = JSON.stringify(CpeLogV1Schema.parse(jsonDoc), null, 2);
  const pdfBody = generateCpeLogPdf(records, args.periodStart, args.periodEnd);

  // 3. Upload both to Storage under an org/user-scoped, unguessable path.
  const base = `cpe-log/${args.orgId}/${args.userId}/${requestId}`;
  const pdfPath = `${base}.pdf`;
  const jsonPath = `${base}.json`;

  const pdfUpload = await deps.storage.upload(bucket, pdfPath, new Uint8Array(pdfBody), 'application/pdf');
  if (pdfUpload.error) {
    throw new Error(`failed to upload CPE log PDF: ${pdfUpload.error.message}`);
  }
  const jsonUpload = await deps.storage.upload(bucket, jsonPath, jsonBody, 'application/json');
  if (jsonUpload.error) {
    throw new Error(`failed to upload CPE log JSON: ${jsonUpload.error.message}`);
  }

  // 4. Sign both.
  const pdfSigned = await deps.storage.createSignedUrl(bucket, pdfPath, SIGNED_URL_TTL_SECONDS);
  if (pdfSigned.error || !pdfSigned.signedUrl) {
    throw new Error(`failed to sign CPE log PDF URL: ${pdfSigned.error?.message ?? 'no url'}`);
  }
  const jsonSigned = await deps.storage.createSignedUrl(bucket, jsonPath, SIGNED_URL_TTL_SECONDS);
  if (jsonSigned.error || !jsonSigned.signedUrl) {
    throw new Error(`failed to sign CPE log JSON URL: ${jsonSigned.error?.message ?? 'no url'}`);
  }

  // 5. Audit (metadata only — non-fatal).
  await emitCpeLogExportedAudit(deps, {
    userId: args.userId,
    orgId: args.orgId,
    periodStart: args.periodStart,
    periodEnd: args.periodEnd,
    recordCount,
    requestId,
  });

  deps.logger.info(
    { requestId, orgId: args.orgId, recordCount },
    'CPE compliance log exported',
  );

  return {
    request_id: requestId,
    record_count: recordCount,
    disclaimer: NASBA_DISCLAIMER_TEXT,
    exports: {
      pdf: { signed_url: pdfSigned.signedUrl, path: pdfPath, expires_in: SIGNED_URL_TTL_SECONDS },
      json: { signed_url: jsonSigned.signedUrl, path: jsonPath, expires_in: SIGNED_URL_TTL_SECONDS },
    },
  };
}
