/**
 * CPE Compliance-Log Export Worker (SCRUM-1860 / SCRUM-1848 — CPE-R2)
 *
 * Generates an auditor-ready CPE (Continuing Professional Education) compliance
 * log for a CPA over a reporting period, in both PDF and JSON form, uploads each
 * artifact to Supabase Storage, and returns a short-lived signed URL for each.
 *
 * It also emits a `cpe_log.exported` audit event carrying METADATA ONLY
 * (actor, period, format, record count, request id) — never any export body
 * content (CC7 no-content-leak).
 *
 * Constitution refs:
 *   - 1.4  : never log PII; only public_id + counts. Service-role DB access.
 *   - 1.5  : timestamps in UTC; "Network Observed Time" framing for chain time.
 *   - 1.6  : worker-only — never imports client-side fingerprint code.
 *   - 1.8  : `cpe_log_v1` JSON schema is additive/frozen-friendly.
 *
 * NASBA framing: this log is informational. Arkova is not affiliated with NASBA
 * or any state board; compliance determination stays with the licensee/board.
 * The mandatory disclaimer below is rendered verbatim into the PDF and embedded
 * in the JSON document.
 */
import { randomUUID } from 'node:crypto';
import { Buffer } from 'node:buffer';
import { jsPDF } from 'jspdf';
import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Logger } from '../utils/logger.js';
import { config } from '../config.js';
import {
  asString,
  asNumber,
  asDateOnly,
  stripTrailingSlashes,
  formatUtc,
  uploadAndSignExportArtifacts,
  assertExportsBucketReady,
} from './export-format-helpers.js';

// Re-export the canonical private-bucket guard (now defined beside the shared
// upload seam in `export-format-helpers.ts`, so `uploadAndSignExportArtifacts`
// can call it without an import cycle) under its historical name, so existing
// callers/tests/docs that import `assertExportsBucketReady` from this module
// keep working. `CpeExportStorage` structurally satisfies its `getBucket` seam.
export { assertExportsBucketReady };

/** Stable, versioned JSON export schema tag. */
export const CPE_LOG_SCHEMA_VERSION = 'cpe_log_v1' as const;

/**
 * Mandatory NASBA disclaimer — rendered VERBATIM into the PDF and embedded in
 * the JSON document. Do not reword; auditors and the state board rely on this
 * exact non-affiliation statement.
 */
export const NASBA_DISCLAIMER_TEXT =
  'This log is generated by Arkova. Arkova is not affiliated with NASBA or any state board of accountancy. CPE compliance determination remains the responsibility of the licensee and their state board.';

/**
 * Default Storage bucket for generated exports (overridable via deps).
 * Read from the worker config module (SCRUM-1258 — no ad-hoc process.env
 * reads outside config.ts). `config.exportsStorageBucket` resolves
 * `EXPORTS_STORAGE_BUCKET || 'exports'`, identical to the prior inline read.
 */
const DEFAULT_EXPORTS_BUCKET = config.exportsStorageBucket;

/** Signed-URL lifetime: 1 hour. Matches the per-user export cadence. */
export const SIGNED_URL_TTL_SECONDS = 3600;

/** Cap records per export to keep generation bounded (perf + memory). */
const MAX_EXPORT_RECORDS = 5000;

// ─── Anchor row shape (worker query projection) ──────
export interface CpeExportAnchorRow {
  id: string;
  public_id: string | null;
  org_id: string | null;
  user_id: string | null;
  label: string | null;
  filename: string | null;
  status: string;
  issued_at: string | null;
  chain_timestamp: string | null;
  created_at: string;
  credential_type: string | null;
  metadata: Record<string, unknown> | null;
  cpe_metadata: Record<string, unknown> | null;
}

// ─── cpe_log_v1 schema (frozen / additive-friendly) ──
/**
 * Per-credential record. Every field is nullable so a partially-extracted
 * anchor still exports cleanly. `extraction_confidence` / `extraction_source`
 * are DELIBERATELY ABSENT — they are internal-only signals, never exported.
 */
export const CpeLogRecordSchema = z
  .object({
    public_id: z.string().nullable(),
    title: z.string().nullable(),
    provider: z.string().nullable(),
    nasba_status: z.string().nullable(),
    cpe_hours: z.number().nullable(),
    field_of_study: z.string().nullable(),
    delivery_method: z.string().nullable(),
    completion_date: z.string().nullable(),
    verification_url: z.string().nullable(),
    anchor_timestamp: z.string().nullable(),
    evidence_level: z.string().nullable(),
    status: z.string(),
  })
  .strict();

export type CpeLogRecord = z.infer<typeof CpeLogRecordSchema>;

// NOTE (round-1 review): CpeLogRecordSchema/CpeLogV1Schema are INTERNAL-ONLY
// validators — they check OUR OWN generated artifact before upload and are not
// published to external consumers (no SDK/docs export references them). The
// `.strict()` is therefore safe: it can never reject a third party's payload,
// only catch our own drift at generation time. If these schemas are ever
// exported for external parsing, `.strict()` must be revisited (§1.8 additive
// evolution would break strict consumers).
export const CpeLogV1Schema = z
  .object({
    schema: z.literal(CPE_LOG_SCHEMA_VERSION),
    generated_at: z.string(),
    period: z.object({ start: z.string(), end: z.string() }).strict(),
    record_count: z.number().int().nonnegative(),
    /**
     * SCRUM-2378 (CPE-01): count of in-period records EXCLUDED because they are
     * not yet SECURED. Additive + optional (§1.8) so previously-issued
     * documents without the field still validate. Always emitted for new
     * exports — un-SECURED records are excluded, counted, and surfaced; never
     * silently dropped and never blocking the export.
     */
    excluded_count: z.number().int().nonnegative().optional(),
    records: z.array(CpeLogRecordSchema),
    disclaimer: z.literal(NASBA_DISCLAIMER_TEXT),
  })
  .strict();

export type CpeLogV1Document = z.infer<typeof CpeLogV1Schema>;

// ─── Storage adapter (DI — no Storage migration required) ──
/**
 * Thin Storage seam so the worker can be unit-tested without a live Supabase
 * Storage bucket, and so the bucket can be provisioned as an ops step rather
 * than a DB migration (keeps this change T2, not T3).
 */
export interface CpeExportStorage {
  upload(
    bucket: string,
    path: string,
    body: Uint8Array | string,
    contentType?: string,
  ): Promise<{ error: Error | null }>;
  createSignedUrl(
    bucket: string,
    path: string,
    expiresIn: number,
  ): Promise<{ signedUrl: string | null; error: Error | null }>;
  /**
   * Inspect a bucket's existence + visibility. Returns `exists: false` when the
   * bucket is absent so the fail-loud guard can raise a clear error instead of
   * a confusing downstream upload 500, and `isPublic` so a misconfigured PUBLIC
   * bucket — which would expose unsigned export bodies (CC7) — is rejected too.
   */
  getBucket(
    bucket: string,
  ): Promise<{ exists: boolean; isPublic: boolean | null; error: Error | null }>;
}

/** Default Storage adapter backed by the Supabase service-role client. */
export function createSupabaseStorageAdapter(db: SupabaseClient): CpeExportStorage {
  // The generated DB types don't model the Storage API; narrow locally.
  const storage = (db as unknown as { storage: {
    from(bucket: string): {
      upload(path: string, body: Uint8Array | string, opts: { contentType?: string; upsert?: boolean }):
        Promise<{ error: Error | null }>;
      createSignedUrl(path: string, expiresIn: number):
        Promise<{ data: { signedUrl: string } | null; error: Error | null }>;
    };
    getBucket(bucket: string):
      Promise<{ data: { public: boolean } | null; error: Error | null }>;
  } }).storage;

  return {
    async upload(bucket, path, body, contentType) {
      const { error } = await storage
        .from(bucket)
        .upload(path, body, { contentType, upsert: true });
      return { error };
    },
    async createSignedUrl(bucket, path, expiresIn) {
      const { data, error } = await storage.from(bucket).createSignedUrl(path, expiresIn);
      return { signedUrl: data?.signedUrl ?? null, error };
    },
    async getBucket(bucket) {
      const { data, error } = await storage.getBucket(bucket);
      // A missing bucket comes back as `data: null` (often with a "not found"
      // error). Surface existence + visibility; the caller's guard decides.
      return { exists: data != null, isPublic: data?.public ?? null, error };
    },
  };
}

export interface CpeLogExportDeps {
  db: SupabaseClient;
  storage: CpeExportStorage;
  logger: Pick<Logger, 'info' | 'warn' | 'error'>;
  /** Public app base URL for building per-credential verification links. */
  frontendUrl: string;
  /** Storage bucket override (defaults to EXPORTS_STORAGE_BUCKET or `exports`). */
  bucket?: string;
  /**
   * Fetch-cap override (defaults to MAX_EXPORT_RECORDS). Test seam only — lets
   * the cap-displacement behavior be exercised without 5000-row fixtures.
   */
  maxRecords?: number;
}

export interface CpeLogExportArgs {
  userId: string;
  orgId: string;
  periodStart: string; // YYYY-MM-DD (inclusive)
  periodEnd: string; // YYYY-MM-DD (inclusive)
  requestId?: string;
}

export interface CpeLogExportArtifact {
  signed_url: string;
  path: string;
  expires_in: number;
}

export interface CpeLogExportResult {
  request_id: string;
  record_count: number;
  /** In-period records excluded because they are not yet SECURED (SCRUM-2378). */
  excluded_count: number;
  disclaimer: string;
  exports: {
    pdf: CpeLogExportArtifact;
    json: CpeLogExportArtifact;
  };
}

// ─── Field mapping helpers ───────────────────────────
// asString / asNumber / asDateOnly / stripTrailingSlashes / formatUtc are
// shared with the CLE exporter and live in ./export-format-helpers.ts.

/**
 * Map a single anchor row to a public-safe CPE log record.
 *
 * Field sources (per SCRUM-1848 AC):
 *   title           ← metadata.credential_title → label → filename
 *   provider        ← cpe_metadata.sponsor_id is an ID, not a name; the human
 *                     provider name lives in metadata.credential_issuer /
 *                     source_provider
 *   nasba_status    ← cpe_metadata.nasba_status
 *   cpe_hours       ← cpe_metadata.credit_hours
 *   field_of_study  ← cpe_metadata.field_of_study
 *   delivery_method ← cpe_metadata.delivery_method
 *   completion_date ← issued_at (fallback metadata.credential_issued_at)
 *   verification_url← `${frontendUrl}/verify/${public_id}`
 *   anchor_timestamp← chain_timestamp (Network Observed Time)
 *   evidence_level  ← metadata.verification_level
 *
 * extraction_confidence / extraction_source are intentionally NOT mapped.
 */
export function buildCpeLogRecord(
  anchor: CpeExportAnchorRow,
  frontendUrl: string,
): CpeLogRecord {
  const meta = (anchor.metadata ?? {}) as Record<string, unknown>;
  const cpe = (anchor.cpe_metadata ?? {}) as Record<string, unknown>;

  const title =
    asString(meta.credential_title) ?? asString(anchor.label) ?? asString(anchor.filename);
  const provider = asString(meta.credential_issuer) ?? asString(meta.source_provider);
  const completion = asDateOnly(anchor.issued_at) ?? asDateOnly(meta.credential_issued_at);
  const verificationUrl = anchor.public_id
    ? `${stripTrailingSlashes(frontendUrl)}/verify/${anchor.public_id}`
    : null;

  return {
    public_id: anchor.public_id,
    title,
    provider,
    nasba_status: asString(cpe.nasba_status),
    cpe_hours: asNumber(cpe.credit_hours),
    field_of_study: asString(cpe.field_of_study),
    delivery_method: asString(cpe.delivery_method),
    completion_date: completion,
    verification_url: verificationUrl,
    anchor_timestamp: anchor.chain_timestamp,
    evidence_level: asString(meta.verification_level),
    status: anchor.status,
  };
}

// ─── PDF rendering ───────────────────────────────────
function generateCpeLogPdf(
  records: CpeLogRecord[],
  periodStart: string,
  periodEnd: string,
): Buffer {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ── Title ──
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Arkova CPE Compliance Log', margin, y);
  y += 9;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${formatUtc(new Date().toISOString())}`, margin, y);
  y += 4;
  doc.text(`Reporting Period: ${periodStart} to ${periodEnd}`, margin, y);
  y += 4;
  doc.text(`Records: ${records.length}`, margin, y);
  y += 8;

  // ── Mandatory NASBA disclaimer (verbatim) ──
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 6;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(90, 90, 90);
  const disclaimerLines = doc.splitTextToSize(NASBA_DISCLAIMER_TEXT, contentWidth);
  doc.text(disclaimerLines, margin, y);
  y += disclaimerLines.length * 4 + 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 8;

  // ── Records ──
  doc.setTextColor(0, 0, 0);
  for (const r of records) {
    if (y > 255) {
      doc.addPage();
      y = margin;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    // Wrap the title explicitly and advance y by the rendered line count, so a
    // long multi-line title does not overlap the Provider line below (mirrors
    // how the disclaimer is rendered). `maxWidth` alone wraps the glyphs but
    // does not tell us how many lines were drawn.
    const titleLines: string[] = doc.splitTextToSize(r.title ?? '(untitled)', contentWidth);
    const TITLE_LINE_HEIGHT = 5;
    doc.text(titleLines, margin, y);
    y += titleLines.length * TITLE_LINE_HEIGHT;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(70, 70, 70);
    const line1 = [
      `Provider: ${r.provider ?? '—'}`,
      `NASBA Status: ${r.nasba_status ?? '—'}`,
      `CPE Hours: ${r.cpe_hours ?? '—'}`,
    ].join('   |   ');
    doc.text(line1, margin, y, { maxWidth: contentWidth });
    y += 4;
    const line2 = [
      `Field of Study: ${r.field_of_study ?? '—'}`,
      `Delivery: ${r.delivery_method ?? '—'}`,
      `Evidence Level: ${r.evidence_level ?? '—'}`,
    ].join('   |   ');
    doc.text(line2, margin, y, { maxWidth: contentWidth });
    y += 4;
    const line3 = [
      `Completion: ${r.completion_date ?? '—'}`,
      `Network Observed Time: ${formatUtc(r.anchor_timestamp)}`,
    ].join('   |   ');
    doc.text(line3, margin, y, { maxWidth: contentWidth });
    y += 4;
    if (r.verification_url) {
      doc.setTextColor(40, 90, 160);
      doc.text(`Verify: ${r.verification_url}`, margin, y, { maxWidth: contentWidth });
      doc.setTextColor(70, 70, 70);
      y += 4;
    }
    y += 3;
  }

  return Buffer.from(doc.output('arraybuffer'));
}

// ─── Audit event (METADATA ONLY — CC7) ───────────────
async function emitCpeLogExportedAudit(
  deps: CpeLogExportDeps,
  args: { userId: string; orgId: string; periodStart: string; periodEnd: string; recordCount: number; excludedCount: number; requestId: string },
): Promise<void> {
  // Only the allowed metadata keys. No titles, providers, public_ids, URLs,
  // or any per-credential content — verified by the CC7 leak test.
  const details = {
    period_start: args.periodStart,
    period_end: args.periodEnd,
    format: 'pdf+json',
    record_count: args.recordCount,
    excluded_count: args.excludedCount,
    request_id: args.requestId,
  };

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any, arkova/missing-org-filter -- audit insert writes a new event row; org_id + actor_id are set on the row (not a tenant-leaking read).
    const result = await (deps.db.from('audit_events') as any).insert({
      event_type: 'cpe_log.exported',
      event_category: 'ADMIN',
      actor_id: args.userId,
      org_id: args.orgId,
      target_type: 'cpe_log_export',
      details: JSON.stringify(details),
    });
    if (result?.error) {
      // Audit failure is non-fatal — the export still succeeded. Log coarse
      // context only (no PII), consistent with worker job conventions.
      deps.logger.warn(
        { orgId: args.orgId, requestId: args.requestId, code: result.error.code },
        'cpe_log.exported audit insert failed (non-fatal)',
      );
    }
  } catch (err) {
    deps.logger.warn(
      { requestId: args.requestId, error: err instanceof Error ? err.message : 'unknown' },
      'cpe_log.exported audit insert threw (non-fatal)',
    );
  }
}

// ─── Orchestration ───────────────────────────────────
/**
 * Generate the CPE compliance log for one user over a period, in both PDF and
 * JSON, upload to Storage, and return signed URLs + a metadata-only audit.
 *
 * Org/user scope: the query is filtered by BOTH `user_id` and `org_id` so a
 * caller can only ever export their own anchors within their org. The endpoint
 * additionally rejects cross-user requests before reaching here (defense in
 * depth).
 */
export async function generateCpeLogExport(
  args: CpeLogExportArgs,
  deps: CpeLogExportDeps,
): Promise<CpeLogExportResult> {
  const requestId = args.requestId ?? randomUUID();
  const bucket = deps.bucket ?? DEFAULT_EXPORTS_BUCKET;

  const maxRecords = deps.maxRecords ?? MAX_EXPORT_RECORDS;

  // 1. Fetch the caller's SECURED CPE anchors in the reporting period.
  //    Service-role client; scope is enforced by the explicit user_id + org_id
  //    filters. `issued_at` is the credential completion date used for the
  //    period window; rows without issued_at are excluded from the period view.
  //
  //    SECURED-only gate (SCRUM-2378 — CPE-01): only records that have reached
  //    `SECURED` are auditor-grade evidence. The status filter runs IN SQL —
  //    not post-fetch — so non-SECURED rows can never displace SECURED rows
  //    inside the fetch cap (round-1 review finding). SECURED-only semantics
  //    conform to the FE-PROOF-GATE contract (docs/reference/FE_PROOF_GATE_CONTRACT.md:
  //    proof evidence is SECURED-only; REVOKED/EXPIRED/SUPERSEDED are never
  //    treated as secured).
  const { data, error } = await deps.db
    .from('anchors')
    .select(
      'id, public_id, org_id, user_id, label, filename, status, issued_at, chain_timestamp, created_at, credential_type, metadata, cpe_metadata',
    )
    .eq('user_id', args.userId)
    .eq('org_id', args.orgId)
    .eq('credential_type', 'CPE')
    .eq('status', 'SECURED')
    .is('deleted_at', null)
    .gte('issued_at', `${args.periodStart}T00:00:00.000Z`)
    .lte('issued_at', `${args.periodEnd}T23:59:59.999Z`)
    .order('issued_at', { ascending: true })
    .limit(maxRecords);

  if (error) {
    throw new Error(`failed to load CPE anchors for export: ${error.message}`);
  }

  const securedAnchors = ((data ?? []) as CpeExportAnchorRow[]).slice(0, maxRecords);

  // 1b. Excluded (non-SECURED) records are counted via a SEPARATE count query
  //     over the same period predicate — never derived from the capped fetch,
  //     which would undercount once the cap is hit. Surfaced as
  //     `excluded_count` in the result, the JSON document, and the audit
  //     event; never silently dropped and never blocking the export.
  //
  //     R0-8 / SCRUM-1254 justification (PR #1415, label `count-exact-allowed`):
  //     `excluded_count` is rendered to the user as an EXACT integer
  //     ("N records aren't included because they aren't secured." —
  //     src/lib/copy.ts EXCLUDED_NOTICE), so an approximate planned/estimated
  //     count would make the notice dishonest. Unlike the whole-table exact
  //     count the R0-8 rule targets (unfiltered scans of the ~3M-row anchors
  //     table that hit the 60s PostgREST timeout), THIS count is tightly
  //     bounded and index-backed: it is filtered to one caller's own anchors
  //     (`user_id` + `org_id`) of a single `credential_type` inside a date
  //     window — a small slice, not a table scan. Exact is both correct and
  //     safe here; the increase is sanctioned via the `count-exact-allowed`
  //     override, not a rule weakening for hot-path counts.
  const excludedRes = await deps.db
    .from('anchors')
    .select('id', { count: 'exact', head: true })
    .eq('user_id', args.userId)
    .eq('org_id', args.orgId)
    .eq('credential_type', 'CPE')
    .neq('status', 'SECURED')
    .is('deleted_at', null)
    .gte('issued_at', `${args.periodStart}T00:00:00.000Z`)
    .lte('issued_at', `${args.periodEnd}T23:59:59.999Z`);

  if (excludedRes.error) {
    // Fail loud rather than emit a fabricated/incomplete exclusion count —
    // excluded_count is an honesty surface (§1.5), not decoration.
    throw new Error(`failed to count excluded CPE records: ${excludedRes.error.message}`);
  }
  const excludedCount = excludedRes.count ?? 0;

  const records = securedAnchors.map((a) => buildCpeLogRecord(a, deps.frontendUrl));
  const recordCount = records.length;

  // 2. Build artifacts.
  const jsonDoc: CpeLogV1Document = {
    schema: CPE_LOG_SCHEMA_VERSION,
    generated_at: new Date().toISOString(),
    period: { start: args.periodStart, end: args.periodEnd },
    record_count: recordCount,
    excluded_count: excludedCount,
    records,
    disclaimer: NASBA_DISCLAIMER_TEXT,
  };
  // Validate our own output against the frozen schema before shipping it.
  const jsonBody = JSON.stringify(CpeLogV1Schema.parse(jsonDoc), null, 2);
  const pdfBody = generateCpeLogPdf(records, args.periodStart, args.periodEnd);

  // 3+4. Upload both artifacts to an org/user-scoped, unguessable base path and
  //      sign each — via the shared generic upload/sign seam. That helper runs
  //      the private-bucket preflight (`assertExportsBucketReady`) exactly once
  //      BEFORE any body is written, so a missing/public bucket fails loud here
  //      too — the guard lives inside the shared seam, not skippably per
  //      exporter (PR #1415, Carson [P1]).
  const base = `cpe-log/${args.orgId}/${args.userId}/${requestId}`;
  const exports = await uploadAndSignExportArtifacts({
    storage: deps.storage,
    bucket,
    basePath: base,
    pdfBody: new Uint8Array(pdfBody),
    jsonBody,
    expiresIn: SIGNED_URL_TTL_SECONDS,
    label: 'CPE',
  });

  // 5. Audit (metadata only — non-fatal).
  await emitCpeLogExportedAudit(deps, {
    userId: args.userId,
    orgId: args.orgId,
    periodStart: args.periodStart,
    periodEnd: args.periodEnd,
    recordCount,
    excludedCount,
    requestId,
  });

  deps.logger.info(
    { requestId, orgId: args.orgId, recordCount, excludedCount },
    'CPE compliance log exported',
  );

  return {
    request_id: requestId,
    record_count: recordCount,
    excluded_count: excludedCount,
    disclaimer: NASBA_DISCLAIMER_TEXT,
    exports,
  };
}
