#!/usr/bin/env -S npx tsx
/**
 * SCRUM-1668 addendum — staging-honesty preflight.
 *
 * Queries a Supabase staging database and reports whether the environment
 * is clean or has migration artifacts left over from prior PR soaks,
 * purges, or fixture seeding.
 *
 * Usage:
 *   npx tsx scripts/ci/staging-honesty-preflight.ts \
 *     --project-ref ujtlwnoqfhtitcmsnrpq \
 *     --format json
 *
 * Connection:
 *   --project-ref  Supabase project ref (or STAGING_PROJECT_REF env var).
 *                  URL derived as https://<ref>.supabase.co
 *   --prod-project-ref  Production Supabase project ref (or PROD_PROJECT_REF
 *                  env var). When paired with a Management API token, the
 *                  prod ledger and prod cron facts are queried live.
 *   --supabase-url Override the derived URL directly.
 *   --service-role-key  Service role key (or SUPABASE_SERVICE_ROLE_KEY env).
 *   --management-api-token  Supabase Management API token (or
 *                  SUPABASE_ACCESS_TOKEN / SUPABASE_MANAGEMENT_API_TOKEN env)
 *                  used as a read-only fallback when supabase_migrations is
 *                  hidden from PostgREST.
 *
 * Checks:
 *   1. PR-only / staging-only rows (timestamp versions, pr695_/pr697_/
 *      staging_purge_/staging_only_ prefixes)
 *   2. Duplicate migration names
 *   3. Duplicate migration versions
 *   4. Known artifact rows (hardcoded list)
 *   5. Missing SUBMITTED anchors
 *   6. Prod ledger divergence
 *   7. Org topology (single-tenant prod vs multi-org staging seeds)
 *   8. Prod facts (pg_cron vacuum-anchors, refresh_pipeline_dashboard_cache)
 *
 * Exit 0 = all checks pass (clean_mirror).
 * Exit 1 = at least one check failed.
 */

import { createClient } from '@supabase/supabase-js';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface MigrationRow {
  version: string;
  name: string;
}

export interface ArtifactClassification {
  row: MigrationRow;
  reason: string;
}

export interface CheckResult {
  name: string;
  passed: boolean;
  details: string;
}

export type EnvironmentType = 'clean_mirror' | 'soak_artifact' | 'fixture_seeded';

export interface PreflightReport {
  environment_type: EnvironmentType;
  staging_project_ref: string;
  timestamp: string;
  checks: CheckResult[];
  artifact_rows: MigrationRow[];
  missing_from_staging: string[];
  extra_vs_prod: string[];
}

export interface OrgTopologyData {
  totalOrgs: number;
  seedOrgs: number;
}

export interface ProdFactsData {
  cronJobNames: string[];
  functionExists: boolean;
}

export interface ParsedArgs {
  projectRef: string | undefined;
  prodProjectRef: string | undefined;
  supabaseUrl: string | undefined;
  serviceRoleKey: string | undefined;
  managementApiToken: string | undefined;
  prodVersions: string[];
  prodFacts: ProdFactsData | undefined;
  format: 'json' | 'text';
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEFAULT_PROD_VERSIONS = ['00000000000000', '0294', '0295', '0296', '0297'];

/** Names that are categorically known artifacts from prior soak runs. */
const KNOWN_ARTIFACT_NAMES = new Set([
  'pr695_0292',
  'pr695_0293',
  'pr697_0290',
  'staging_purge_v5',
  'staging_purge_v6',
]);

/** Name that becomes an artifact only when it appears more than once. */
const KNOWN_DUPLICATE_NAME = '0294_refund_org_credit';

/**
 * Prefixes in migration names that indicate staging-only or PR-only rows.
 * Checked with `startsWith` against the lowercased name.
 */
const STAGING_NAME_PREFIXES = ['pr695_', 'pr697_', 'staging_purge_', 'staging_only_'];

/**
 * A version with 14+ digits is a Supabase timestamp migration (yyyyMMddHHmmss)
 * generated by preview branches or manual `supabase migration new`. These are
 * never canonical.
 *
 * Exception: '00000000000000' is the init row and always canonical.
 */
const TIMESTAMP_VERSION_RE = /^\d{14,}$/;

/** Prefixes in org names that indicate staging seed data (case-insensitive). */
const SEED_ORG_PREFIXES = ['stg', 'staging_seed_', 'test_org_'];

const MANAGEMENT_API_BASE_URL = 'https://api.supabase.com/v1';
const MIGRATION_LEDGER_QUERY = `
  select version, name
  from supabase_migrations.schema_migrations
  order by version asc
`;
const MIGRATION_VERSION_QUERY = `
  select version
  from supabase_migrations.schema_migrations
  order by version asc
`;
const CRON_JOB_NAMES_QUERY = `
  select coalesce(jsonb_agg(jobname order by jobname), '[]'::jsonb) as cron_job_names
  from cron.job
`;
const REFRESH_FUNCTION_EXISTS_QUERY = `
  select to_regprocedure('public.refresh_pipeline_dashboard_cache()') is not null as function_exists
`;

// ---------------------------------------------------------------------------
// Pure classification functions (exported for testing)
// ---------------------------------------------------------------------------

/**
 * Classify a single migration row. Returns null if the row looks canonical,
 * or an ArtifactClassification describing why it is suspect.
 */
export function classifyMigrationRow(row: MigrationRow): ArtifactClassification | null {
  const { version, name } = row;

  // The init row is always canonical.
  if (version === '00000000000000') return null;

  // Timestamp-format version (14+ digits, but not the init row).
  if (TIMESTAMP_VERSION_RE.test(version)) {
    return { row, reason: `timestamp version (${version}) — likely preview-branch or staging-only` };
  }

  // Known staging/PR prefixes in name.
  const lowerName = name.toLowerCase();
  for (const prefix of STAGING_NAME_PREFIXES) {
    if (lowerName.startsWith(prefix)) {
      return { row, reason: `name starts with ${prefix}` };
    }
  }

  return null;
}

/**
 * Generic duplicate finder — returns values of `field` that appear more than once.
 */
function findDuplicates(rows: MigrationRow[], field: keyof MigrationRow): string[] {
  const counts = new Map<string, number>();
  for (const row of rows) {
    const val = row[field];
    counts.set(val, (counts.get(val) ?? 0) + 1);
  }
  return [...counts.entries()].filter(([, count]) => count > 1).map(([val]) => val);
}

/**
 * Find migration names that appear more than once.
 */
export function findDuplicateNames(rows: MigrationRow[]): string[] {
  return findDuplicates(rows, 'name');
}

/**
 * Find migration versions that appear more than once.
 */
export function findDuplicateVersions(rows: MigrationRow[]): string[] {
  return findDuplicates(rows, 'version');
}

/**
 * Detect rows that match the hardcoded known-artifact list.
 * Also flags duplicate occurrences of KNOWN_DUPLICATE_NAME.
 */
export function detectKnownArtifacts(rows: MigrationRow[]): MigrationRow[] {
  const artifacts: MigrationRow[] = [];

  // Track how many times the known-duplicate name appears.
  let duplicateNameCount = 0;

  for (const row of rows) {
    if (KNOWN_ARTIFACT_NAMES.has(row.name)) {
      artifacts.push(row);
      continue;
    }
    if (row.name === KNOWN_DUPLICATE_NAME) {
      duplicateNameCount++;
      if (duplicateNameCount > 1) {
        // Flag the second (and subsequent) occurrence.
        artifacts.push(row);
      }
    }
  }

  return artifacts;
}

export function isSupabaseMigrationsSchemaUnavailable(
  error: { code?: string; message?: string } | null | undefined,
): boolean {
  const code = error?.code?.toUpperCase();
  const message = error?.message?.toLowerCase() ?? '';
  return code === 'PGRST106'
    || message.includes('schema must be one of')
    || (message.includes('supabase_migrations') && message.includes('invalid schema'));
}

function normalizeMigrationVersion(value: unknown): string | null {
  const raw = String(value ?? '').trim();
  if (!raw) return null;
  if (raw === '00000000000000') return raw;
  if (/^\d+$/.test(raw) && raw.length < 14) {
    return raw.padStart(4, '0');
  }
  return raw;
}

export function mapManagementMigrationRows(rows: readonly Record<string, unknown>[]): MigrationRow[] {
  return rows.flatMap((row) => {
    const version = normalizeMigrationVersion(row.version);
    if (!version) return [];
    return [{
      version,
      name: String(row.name ?? ''),
    }];
  });
}

export function mapManagementMigrationVersions(rows: readonly Record<string, unknown>[]): string[] {
  return rows.flatMap((row) => {
    const version = normalizeMigrationVersion(row.version);
    return version ? [version] : [];
  });
}

export function mapManagementProdFacts(
  cronRows: readonly Record<string, unknown>[],
  functionRows: readonly Record<string, unknown>[],
): ProdFactsData {
  const cronJobNamesValue = cronRows[0]?.cron_job_names;
  const cronJobNames = Array.isArray(cronJobNamesValue)
    ? cronJobNamesValue.map(String)
    : [];
  return {
    cronJobNames,
    functionExists: functionRows[0]?.function_exists === true,
  };
}

/**
 * Compare staging migration versions against the prod ledger.
 */
export function computeProdDivergence(
  rows: MigrationRow[],
  prodVersions: string[],
): { missingFromStaging: string[]; extraVsProd: string[] } {
  const stagingVersions = new Set(rows.map((r) => r.version));
  const prodSet = new Set(prodVersions);

  const missingFromStaging = prodVersions.filter((v) => !stagingVersions.has(v));
  const extraVsProd = [...stagingVersions].filter((v) => !prodSet.has(v));

  return { missingFromStaging, extraVsProd };
}

/**
 * Check org topology: distinguish single-tenant prod from multi-org staging seeds.
 * Requires org-scoped fixtures (non-seed orgs) when seed orgs are present.
 */
export function checkOrgTopology(data: OrgTopologyData): CheckResult {
  if (data.totalOrgs === 0) {
    return {
      name: 'org_topology',
      passed: false,
      details: 'No organizations found — staging lacks seed data.',
    };
  }

  if (data.seedOrgs === 0) {
    return {
      name: 'org_topology',
      passed: true,
      details: `${data.totalOrgs} org(s), no staging seed orgs — prod-like single-tenant topology.`,
    };
  }

  const fixtureOrgs = data.totalOrgs - data.seedOrgs;
  if (fixtureOrgs > 0) {
    return {
      name: 'org_topology',
      passed: true,
      details: `${data.totalOrgs} org(s) total (${data.seedOrgs} seed, ${fixtureOrgs} org-scoped fixture(s)).`,
    };
  }

  return {
    name: 'org_topology',
    passed: false,
    details: `All ${data.totalOrgs} org(s) are seed-prefixed — no org-scoped fixtures for connector work.`,
  };
}

/**
 * Verify prod facts from the 2026-05-06 correction:
 *   - pg_cron has vacuum-anchors job
 *   - refresh_pipeline_dashboard_cache() exists
 *   - refresh-pipeline-dashboard-cache is scheduled per the SCRUM-1708 cadence
 */
export function checkProdFacts(data: ProdFactsData): CheckResult {
  const issues: string[] = [];

  if (!data.cronJobNames.includes('vacuum-anchors')) {
    issues.push('pg_cron vacuum-anchors job missing');
  }

  if (!data.functionExists) {
    issues.push('refresh_pipeline_dashboard_cache() function missing');
  }

  if (!data.cronJobNames.includes('refresh-pipeline-dashboard-cache')) {
    issues.push('refresh-pipeline-dashboard-cache job missing');
  }

  return {
    name: 'prod_facts',
    passed: issues.length === 0,
    details: issues.length === 0
      ? 'Prod facts verified: vacuum-anchors scheduled, refresh_pipeline_dashboard_cache exists, refresh-pipeline-dashboard-cache scheduled.'
      : `Prod facts divergence: ${issues.join('; ')}.`,
  };
}

/**
 * Classify an org name as a staging seed org (case-insensitive prefix match).
 */
export function isOrgSeedName(name: string): boolean {
  const lower = name.toLowerCase();
  return SEED_ORG_PREFIXES.some((p) => lower.startsWith(p));
}

// ---------------------------------------------------------------------------
// Report builder
// ---------------------------------------------------------------------------

export function buildReport(opts: {
  projectRef: string;
  migrationRows: MigrationRow[];
  submittedAnchorCount: number;
  prodVersions: string[];
  orgTopology?: OrgTopologyData;
  prodFacts?: ProdFactsData;
}): PreflightReport {
  const { projectRef, migrationRows, submittedAnchorCount, prodVersions } = opts;
  const checks: CheckResult[] = [];
  let allArtifactRows: MigrationRow[] = [];

  // Check 1: PR-only / staging-only rows
  const classified = migrationRows
    .map((row) => classifyMigrationRow(row))
    .filter((c): c is ArtifactClassification => c !== null);
  const artifactRowsFromClassification = classified.map((c) => c.row);
  checks.push({
    name: 'staging_only_rows',
    passed: classified.length === 0,
    details: classified.length === 0
      ? 'No PR-only or staging-only migration rows found.'
      : `${classified.length} suspect row(s): ${classified.map((c) => `${c.row.name} (${c.reason})`).join('; ')}`,
  });

  // Check 2: Duplicate names
  const dupeNames = findDuplicateNames(migrationRows);
  checks.push({
    name: 'duplicate_names',
    passed: dupeNames.length === 0,
    details: dupeNames.length === 0
      ? 'No duplicate migration names.'
      : `Duplicate name(s): ${dupeNames.join(', ')}`,
  });

  // Check 3: Duplicate versions
  const dupeVersions = findDuplicateVersions(migrationRows);
  checks.push({
    name: 'duplicate_versions',
    passed: dupeVersions.length === 0,
    details: dupeVersions.length === 0
      ? 'No duplicate migration versions.'
      : `Duplicate version(s): ${dupeVersions.join(', ')}`,
  });

  // Check 4: Known artifact rows
  const knownArtifacts = detectKnownArtifacts(migrationRows);
  checks.push({
    name: 'known_artifacts',
    passed: knownArtifacts.length === 0,
    details: knownArtifacts.length === 0
      ? 'No known artifact rows.'
      : `${knownArtifacts.length} known artifact(s): ${knownArtifacts.map((r) => r.name).join(', ')}`,
  });

  // Check 5: Missing SUBMITTED anchors
  checks.push({
    name: 'submitted_anchors',
    passed: submittedAnchorCount > 0,
    details: submittedAnchorCount > 0
      ? `${submittedAnchorCount} SUBMITTED anchor(s) found.`
      : 'Zero SUBMITTED anchors — environment may lack test fixtures.',
  });

  // Check 6: Prod divergence
  const divergence = computeProdDivergence(migrationRows, prodVersions);
  const prodDiverged = divergence.missingFromStaging.length > 0 || divergence.extraVsProd.length > 0;
  checks.push({
    name: 'prod_divergence',
    passed: !prodDiverged,
    details: prodDiverged
      ? `Missing from staging: [${divergence.missingFromStaging.join(', ')}]; Extra vs prod: [${divergence.extraVsProd.join(', ')}]`
      : 'Staging versions match prod ledger.',
  });

  // Check 7: Org topology (single-tenant prod vs multi-org staging seeds)
  if (opts.orgTopology) {
    checks.push(checkOrgTopology(opts.orgTopology));
  }

  // Check 8: Prod facts (pg_cron, function existence, scheduling)
  if (opts.prodFacts) {
    checks.push(checkProdFacts(opts.prodFacts));
  }

  // Collect all artifact rows (deduplicated by version+name).
  const seen = new Set<string>();
  allArtifactRows = [
    ...artifactRowsFromClassification,
    ...knownArtifacts,
  ].filter((row) => {
    const key = `${row.version}::${row.name}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  // Determine environment type.
  const anyFailed = checks.some((c) => !c.passed);
  const hasArtifacts = allArtifactRows.length > 0
    || dupeNames.length > 0
    || dupeVersions.length > 0
    || classified.length > 0;
  const missingAnchors = submittedAnchorCount === 0;

  let environmentType: EnvironmentType;
  if (!anyFailed) {
    environmentType = 'clean_mirror';
  } else if (hasArtifacts) {
    environmentType = 'soak_artifact';
  } else if (missingAnchors) {
    environmentType = 'fixture_seeded';
  } else {
    // Prod divergence only, no artifacts — still classify as soak_artifact.
    environmentType = 'soak_artifact';
  }

  return {
    environment_type: environmentType,
    staging_project_ref: projectRef,
    timestamp: new Date().toISOString(),
    checks,
    artifact_rows: allArtifactRows,
    missing_from_staging: divergence.missingFromStaging,
    extra_vs_prod: divergence.extraVsProd,
  };
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

export function parseArgs(argv: string[]): ParsedArgs {
  let projectRef: string | undefined;
  let prodProjectRef: string | undefined;
  let supabaseUrl: string | undefined;
  let serviceRoleKey: string | undefined;
  let managementApiToken: string | undefined;
  let prodVersions: string[] = DEFAULT_PROD_VERSIONS;
  let prodFacts: ProdFactsData | undefined;
  let format: 'json' | 'text' = 'json';

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = argv[i + 1];
    switch (arg) {
      case '--project-ref':
        projectRef = next;
        i++;
        break;
      case '--prod-project-ref':
        prodProjectRef = next;
        i++;
        break;
      case '--supabase-url':
        supabaseUrl = next;
        i++;
        break;
      case '--service-role-key':
        serviceRoleKey = next;
        i++;
        break;
      case '--management-api-token':
        managementApiToken = next;
        i++;
        break;
      case '--prod-versions':
        prodVersions = next?.split(',').map((v) => v.trim()).filter(Boolean) ?? DEFAULT_PROD_VERSIONS;
        i++;
        break;
      case '--prod-facts':
        try {
          prodFacts = JSON.parse(next) as ProdFactsData;
        } catch { /* ignore malformed JSON */ }
        i++;
        break;
      case '--format':
        format = next === 'text' ? 'text' : 'json';
        i++;
        break;
    }
  }

  return { projectRef, prodProjectRef, supabaseUrl, serviceRoleKey, managementApiToken, prodVersions, prodFacts, format };
}

// ---------------------------------------------------------------------------
// Text formatter
// ---------------------------------------------------------------------------

function formatText(report: PreflightReport): string {
  const lines: string[] = [];
  lines.push('='.repeat(60));
  lines.push(`Staging Honesty Preflight — ${report.environment_type.toUpperCase()}`);
  lines.push(`Project: ${report.staging_project_ref}`);
  lines.push(`Time:    ${report.timestamp}`);
  lines.push('='.repeat(60));
  lines.push('');

  for (const check of report.checks) {
    const icon = check.passed ? '[PASS]' : '[FAIL]';
    lines.push(`${icon} ${check.name}`);
    lines.push(`       ${check.details}`);
  }

  if (report.artifact_rows.length > 0) {
    lines.push('');
    lines.push('Artifact rows:');
    for (const row of report.artifact_rows) {
      lines.push(`  version=${row.version}  name=${row.name}`);
    }
  }

  if (report.missing_from_staging.length > 0) {
    lines.push('');
    lines.push(`Missing from staging: ${report.missing_from_staging.join(', ')}`);
  }
  if (report.extra_vs_prod.length > 0) {
    lines.push('');
    lines.push(`Extra vs prod: ${report.extra_vs_prod.join(', ')}`);
  }

  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main (DB-connected)
// ---------------------------------------------------------------------------

async function queryManagementApi(projectRef: string, managementApiToken: string, query: string): Promise<Record<string, unknown>[]> {
  const response = await fetch(`${MANAGEMENT_API_BASE_URL}/projects/${encodeURIComponent(projectRef)}/database/query/read-only`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${managementApiToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query }),
  });

  if (!response.ok) {
    throw new Error(`Supabase Management API query failed (${response.status})`);
  }

  const payload = await response.json() as unknown;
  if (!Array.isArray(payload)) {
    throw new Error('Supabase Management API query returned a non-array payload.');
  }
  return payload.filter((row): row is Record<string, unknown> => row !== null && typeof row === 'object' && !Array.isArray(row));
}

async function fetchMigrationRowsViaManagementApi(projectRef: string, managementApiToken: string): Promise<MigrationRow[]> {
  const rows = await queryManagementApi(projectRef, managementApiToken, MIGRATION_LEDGER_QUERY);
  return mapManagementMigrationRows(rows);
}

async function fetchMigrationVersionsViaManagementApi(projectRef: string, managementApiToken: string): Promise<string[]> {
  const rows = await queryManagementApi(projectRef, managementApiToken, MIGRATION_VERSION_QUERY);
  return mapManagementMigrationVersions(rows);
}

async function fetchProdFactsViaManagementApi(projectRef: string, managementApiToken: string): Promise<ProdFactsData> {
  const [cronRows, functionRows] = await Promise.all([
    queryManagementApi(projectRef, managementApiToken, CRON_JOB_NAMES_QUERY),
    queryManagementApi(projectRef, managementApiToken, REFRESH_FUNCTION_EXISTS_QUERY),
  ]);
  return mapManagementProdFacts(cronRows, functionRows);
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  const projectRef = args.projectRef ?? process.env.STAGING_PROJECT_REF;
  const prodProjectRef = args.prodProjectRef ?? process.env.PROD_PROJECT_REF;
  const serviceRoleKey = args.serviceRoleKey ?? process.env.SUPABASE_SERVICE_ROLE_KEY;
  const managementApiToken = args.managementApiToken
    ?? process.env.SUPABASE_ACCESS_TOKEN
    ?? process.env.SUPABASE_MANAGEMENT_API_TOKEN;
  const supabaseUrl = args.supabaseUrl
    ?? (projectRef ? `https://${projectRef}.supabase.co` : undefined);

  if (!supabaseUrl) {
    console.error('::error::Missing --project-ref / STAGING_PROJECT_REF or --supabase-url.');
    process.exit(1);
  }
  if (!serviceRoleKey) {
    console.error('::error::Missing --service-role-key / SUPABASE_SERVICE_ROLE_KEY.');
    process.exit(1);
  }

  const client = createClient(supabaseUrl, serviceRoleKey, {
    db: { schema: 'supabase_migrations' },
  });

  // Query migration rows.
  const { data: migrationData, error: migrationError } = await client
    .from('schema_migrations')
    .select('version, name')
    .order('version', { ascending: true });

  let migrationRows: MigrationRow[];
  if (migrationError) {
    if (isSupabaseMigrationsSchemaUnavailable(migrationError) && managementApiToken && projectRef) {
      migrationRows = await fetchMigrationRowsViaManagementApi(projectRef, managementApiToken);
    } else {
      const hint = isSupabaseMigrationsSchemaUnavailable(migrationError)
        ? ' Set --management-api-token or SUPABASE_ACCESS_TOKEN to query the ledger through the Supabase Management API.'
        : '';
      console.error(`::error::Failed to query schema_migrations: ${migrationError.message}${hint}`);
      process.exit(1);
    }
  } else {
    migrationRows = mapManagementMigrationRows(migrationData ?? []);
  }

  // Query SUBMITTED anchor count.
  const publicClient = createClient(supabaseUrl, serviceRoleKey);
  const { count, error: anchorError } = await publicClient
    .from('anchors')
    .select('*', { count: 'exact', head: true })
    .eq('status', 'SUBMITTED');

  if (anchorError) {
    console.error(`::error::Failed to query anchors: ${anchorError.message}`);
    process.exit(1);
  }

  // Query org topology (best-effort — organizations table is in public schema).
  let orgTopology: OrgTopologyData | undefined;
  try {
    const { data: orgData, error: orgError } = await publicClient
      .from('organizations')
      .select('name');
    if (!orgError && orgData) {
      const seedOrgs = orgData.filter((o: { name: string }) => isOrgSeedName(o.name)).length;
      orgTopology = { totalOrgs: orgData.length, seedOrgs };
    }
  } catch {
    // Org topology check skipped — table may not exist in this environment.
  }

  let prodVersions = args.prodVersions;
  if (managementApiToken && prodProjectRef) {
    try {
      prodVersions = await fetchMigrationVersionsViaManagementApi(prodProjectRef, managementApiToken);
    } catch {
      console.error('::error::Failed to query prod migration ledger via Management API; refusing to use configured/default prod versions as live prod evidence.');
      process.exit(1);
    }
  }

  // Prod facts: prefer CLI flag, then prod Management API, then environment cron schema.
  let prodFacts: ProdFactsData | undefined = args.prodFacts;
  if (!prodFacts && managementApiToken && prodProjectRef) {
    try {
      prodFacts = await fetchProdFactsViaManagementApi(prodProjectRef, managementApiToken);
    } catch {
      console.error('::error::Failed to query prod facts via Management API; refusing to use staging cron data as prod evidence.');
      process.exit(1);
    }
  }
  if (!prodFacts && !(managementApiToken && prodProjectRef)) {
    try {
      const cronClient = createClient(supabaseUrl, serviceRoleKey, { db: { schema: 'cron' } });
      const { data: cronData, error: cronError } = await cronClient
        .from('job')
        .select('jobname');
      if (!cronError && cronData) {
        const cronJobNames = cronData.map((j: { jobname: string }) => j.jobname);
        const functionExists = cronJobNames.length > 0;
        prodFacts = { cronJobNames, functionExists };
      }
    } catch {
      // Prod facts check skipped — cron schema may not be exposed via PostgREST.
    }
  }

  const report = buildReport({
    projectRef: projectRef ?? supabaseUrl,
    migrationRows,
    submittedAnchorCount: count ?? 0,
    prodVersions,
    orgTopology,
    prodFacts,
  });

  if (args.format === 'text') {
    process.stdout.write(formatText(report));
  } else {
    console.log(JSON.stringify(report, null, 2));
  }

  const allPassed = report.checks.every((c) => c.passed);
  if (allPassed) {
    if (args.format !== 'json') {
      console.log('All checks passed — staging environment is clean.');
    }
  } else {
    process.exit(1);
  }
}

// ---------------------------------------------------------------------------
// Entry-point guard
// ---------------------------------------------------------------------------

function isMainModule(metaUrl: string, argvPath: string | undefined): boolean {
  return argvPath !== undefined && resolve(fileURLToPath(metaUrl)) === resolve(argvPath);
}

if (isMainModule(import.meta.url, process.argv[1])) {
  main().catch((err) => {
    console.error(`::error::Unexpected error: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  });
}
