#!/usr/bin/env -S npx tsx
/**
 * SCRUM-1668 addendum — staging-honesty preflight.
 *
 * Queries a Supabase staging database and reports whether the environment
 * is clean or has migration artifacts left over from prior PR soaks,
 * purges, or fixture seeding.
 *
 * Usage:
 *   npx tsx scripts/ci/staging-honesty-preflight.ts \
 *     --project-ref ujtlwnoqfhtitcmsnrpq \
 *     --format json
 *
 * Connection:
 *   --project-ref  Supabase project ref (or STAGING_PROJECT_REF env var).
 *                  URL derived as https://<ref>.supabase.co
 *   --supabase-url Override the derived URL directly.
 *   --service-role-key  Service role key (or SUPABASE_SERVICE_ROLE_KEY env).
 *
 * Checks:
 *   1. PR-only / staging-only rows (timestamp versions, pr695_/pr697_/
 *      staging_purge_/staging_only_ prefixes)
 *   2. Duplicate migration names
 *   3. Duplicate migration versions
 *   4. Known artifact rows (hardcoded list)
 *   5. Missing SUBMITTED anchors
 *   6. Prod ledger divergence
 *
 * Exit 0 = all checks pass (clean_mirror).
 * Exit 1 = at least one check failed.
 */

import { createClient } from '@supabase/supabase-js';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface MigrationRow {
  version: string;
  name: string;
}

export interface ArtifactClassification {
  row: MigrationRow;
  reason: string;
}

export interface CheckResult {
  name: string;
  passed: boolean;
  details: string;
}

export type EnvironmentType = 'clean_mirror' | 'soak_artifact' | 'fixture_seeded';

export interface PreflightReport {
  environment_type: EnvironmentType;
  staging_project_ref: string;
  timestamp: string;
  checks: CheckResult[];
  artifact_rows: MigrationRow[];
  missing_from_prod: string[];
  extra_vs_prod: string[];
}

export interface ParsedArgs {
  projectRef: string | undefined;
  supabaseUrl: string | undefined;
  serviceRoleKey: string | undefined;
  prodVersions: string[];
  format: 'json' | 'text';
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEFAULT_PROD_VERSIONS = ['00000000000000', '0294', '0295', '0296', '0297'];

/** Names that are categorically known artifacts from prior soak runs. */
const KNOWN_ARTIFACT_NAMES = new Set([
  'pr695_0292',
  'pr695_0293',
  'pr697_0290',
  'staging_purge_v5',
  'staging_purge_v6',
]);

/** Name that becomes an artifact only when it appears more than once. */
const KNOWN_DUPLICATE_NAME = '0294_refund_org_credit';

/**
 * Prefixes in migration names that indicate staging-only or PR-only rows.
 * Checked with `startsWith` against the lowercased name.
 */
const STAGING_NAME_PREFIXES = ['pr695_', 'pr697_', 'staging_purge_', 'staging_only_'];

/**
 * A version with 14+ digits is a Supabase timestamp migration (yyyyMMddHHmmss)
 * generated by preview branches or manual `supabase migration new`. These are
 * never canonical.
 *
 * Exception: '00000000000000' is the init row and always canonical.
 */
const TIMESTAMP_VERSION_RE = /^\d{14,}$/;

// ---------------------------------------------------------------------------
// Pure classification functions (exported for testing)
// ---------------------------------------------------------------------------

/**
 * Classify a single migration row. Returns null if the row looks canonical,
 * or an ArtifactClassification describing why it is suspect.
 */
export function classifyMigrationRow(row: MigrationRow): ArtifactClassification | null {
  const { version, name } = row;

  // The init row is always canonical.
  if (version === '00000000000000' && name === '00000000000000') return null;

  // Timestamp-format version (14+ digits, but not the init row).
  if (TIMESTAMP_VERSION_RE.test(version)) {
    return { row, reason: `timestamp version (${version}) — likely preview-branch or staging-only` };
  }

  // Known staging/PR prefixes in name.
  const lowerName = name.toLowerCase();
  for (const prefix of STAGING_NAME_PREFIXES) {
    if (lowerName.startsWith(prefix)) {
      return { row, reason: `name starts with ${prefix}` };
    }
  }

  return null;
}

/**
 * Find migration names that appear more than once.
 */
export function findDuplicateNames(rows: MigrationRow[]): string[] {
  const counts = new Map<string, number>();
  for (const row of rows) {
    counts.set(row.name, (counts.get(row.name) ?? 0) + 1);
  }
  return [...counts.entries()].filter(([, count]) => count > 1).map(([name]) => name);
}

/**
 * Find migration versions that appear more than once.
 */
export function findDuplicateVersions(rows: MigrationRow[]): string[] {
  const counts = new Map<string, number>();
  for (const row of rows) {
    counts.set(row.version, (counts.get(row.version) ?? 0) + 1);
  }
  return [...counts.entries()].filter(([, count]) => count > 1).map(([version]) => version);
}

/**
 * Detect rows that match the hardcoded known-artifact list.
 * Also flags duplicate occurrences of KNOWN_DUPLICATE_NAME.
 */
export function detectKnownArtifacts(rows: MigrationRow[]): MigrationRow[] {
  const artifacts: MigrationRow[] = [];

  // Track how many times the known-duplicate name appears.
  let duplicateNameCount = 0;
  let firstDuplicateSeen = false;

  for (const row of rows) {
    if (KNOWN_ARTIFACT_NAMES.has(row.name)) {
      artifacts.push(row);
      continue;
    }
    if (row.name === KNOWN_DUPLICATE_NAME) {
      duplicateNameCount++;
      if (duplicateNameCount > 1 && !firstDuplicateSeen) {
        // Flag the second (and subsequent) occurrence.
        artifacts.push(row);
        firstDuplicateSeen = true;
      }
    }
  }

  return artifacts;
}

/**
 * Compare staging migration versions against the prod ledger.
 */
export function computeProdDivergence(
  rows: MigrationRow[],
  prodVersions: string[],
): { missingFromProd: string[]; extraVsProd: string[] } {
  const stagingVersions = new Set(rows.map((r) => r.version));
  const prodSet = new Set(prodVersions);

  const missingFromProd = prodVersions.filter((v) => !stagingVersions.has(v));
  const extraVsProd = [...stagingVersions].filter((v) => !prodSet.has(v));

  return { missingFromProd, extraVsProd };
}

// ---------------------------------------------------------------------------
// Report builder
// ---------------------------------------------------------------------------

export function buildReport(opts: {
  projectRef: string;
  migrationRows: MigrationRow[];
  submittedAnchorCount: number;
  prodVersions: string[];
}): PreflightReport {
  const { projectRef, migrationRows, submittedAnchorCount, prodVersions } = opts;
  const checks: CheckResult[] = [];
  let allArtifactRows: MigrationRow[] = [];

  // Check 1: PR-only / staging-only rows
  const classified = migrationRows
    .map((row) => classifyMigrationRow(row))
    .filter((c): c is ArtifactClassification => c !== null);
  const artifactRowsFromClassification = classified.map((c) => c.row);
  checks.push({
    name: 'staging_only_rows',
    passed: classified.length === 0,
    details: classified.length === 0
      ? 'No PR-only or staging-only migration rows found.'
      : `${classified.length} suspect row(s): ${classified.map((c) => `${c.row.name} (${c.reason})`).join('; ')}`,
  });

  // Check 2: Duplicate names
  const dupeNames = findDuplicateNames(migrationRows);
  checks.push({
    name: 'duplicate_names',
    passed: dupeNames.length === 0,
    details: dupeNames.length === 0
      ? 'No duplicate migration names.'
      : `Duplicate name(s): ${dupeNames.join(', ')}`,
  });

  // Check 3: Duplicate versions
  const dupeVersions = findDuplicateVersions(migrationRows);
  checks.push({
    name: 'duplicate_versions',
    passed: dupeVersions.length === 0,
    details: dupeVersions.length === 0
      ? 'No duplicate migration versions.'
      : `Duplicate version(s): ${dupeVersions.join(', ')}`,
  });

  // Check 4: Known artifact rows
  const knownArtifacts = detectKnownArtifacts(migrationRows);
  checks.push({
    name: 'known_artifacts',
    passed: knownArtifacts.length === 0,
    details: knownArtifacts.length === 0
      ? 'No known artifact rows.'
      : `${knownArtifacts.length} known artifact(s): ${knownArtifacts.map((r) => r.name).join(', ')}`,
  });

  // Check 5: Missing SUBMITTED anchors
  checks.push({
    name: 'submitted_anchors',
    passed: submittedAnchorCount > 0,
    details: submittedAnchorCount > 0
      ? `${submittedAnchorCount} SUBMITTED anchor(s) found.`
      : 'Zero SUBMITTED anchors — environment may lack test fixtures.',
  });

  // Check 6: Prod divergence
  const divergence = computeProdDivergence(migrationRows, prodVersions);
  const prodDiverged = divergence.missingFromProd.length > 0 || divergence.extraVsProd.length > 0;
  checks.push({
    name: 'prod_divergence',
    passed: !prodDiverged,
    details: prodDiverged
      ? `Missing from prod: [${divergence.missingFromProd.join(', ')}]; Extra vs prod: [${divergence.extraVsProd.join(', ')}]`
      : 'Staging versions match prod ledger.',
  });

  // Collect all artifact rows (deduplicated by version+name).
  const seen = new Set<string>();
  allArtifactRows = [
    ...artifactRowsFromClassification,
    ...knownArtifacts,
  ].filter((row) => {
    const key = `${row.version}::${row.name}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  // Determine environment type.
  const anyFailed = checks.some((c) => !c.passed);
  const hasArtifacts = allArtifactRows.length > 0
    || dupeNames.length > 0
    || dupeVersions.length > 0
    || classified.length > 0;
  const missingAnchors = submittedAnchorCount === 0;

  let environmentType: EnvironmentType;
  if (!anyFailed) {
    environmentType = 'clean_mirror';
  } else if (hasArtifacts) {
    environmentType = 'soak_artifact';
  } else if (missingAnchors) {
    environmentType = 'fixture_seeded';
  } else {
    // Prod divergence only, no artifacts — still classify as soak_artifact.
    environmentType = 'soak_artifact';
  }

  return {
    environment_type: environmentType,
    staging_project_ref: projectRef,
    timestamp: new Date().toISOString(),
    checks,
    artifact_rows: allArtifactRows,
    missing_from_prod: divergence.missingFromProd,
    extra_vs_prod: divergence.extraVsProd,
  };
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

export function parseArgs(argv: string[]): ParsedArgs {
  let projectRef: string | undefined;
  let supabaseUrl: string | undefined;
  let serviceRoleKey: string | undefined;
  let prodVersions: string[] = DEFAULT_PROD_VERSIONS;
  let format: 'json' | 'text' = 'json';

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = argv[i + 1];
    switch (arg) {
      case '--project-ref':
        projectRef = next;
        i++;
        break;
      case '--supabase-url':
        supabaseUrl = next;
        i++;
        break;
      case '--service-role-key':
        serviceRoleKey = next;
        i++;
        break;
      case '--prod-versions':
        prodVersions = next?.split(',').map((v) => v.trim()).filter(Boolean) ?? DEFAULT_PROD_VERSIONS;
        i++;
        break;
      case '--format':
        format = next === 'text' ? 'text' : 'json';
        i++;
        break;
    }
  }

  return { projectRef, supabaseUrl, serviceRoleKey, prodVersions, format };
}

// ---------------------------------------------------------------------------
// Text formatter
// ---------------------------------------------------------------------------

function formatText(report: PreflightReport): string {
  const lines: string[] = [];
  lines.push('='.repeat(60));
  lines.push(`Staging Honesty Preflight — ${report.environment_type.toUpperCase()}`);
  lines.push(`Project: ${report.staging_project_ref}`);
  lines.push(`Time:    ${report.timestamp}`);
  lines.push('='.repeat(60));
  lines.push('');

  for (const check of report.checks) {
    const icon = check.passed ? '[PASS]' : '[FAIL]';
    lines.push(`${icon} ${check.name}`);
    lines.push(`       ${check.details}`);
  }

  if (report.artifact_rows.length > 0) {
    lines.push('');
    lines.push('Artifact rows:');
    for (const row of report.artifact_rows) {
      lines.push(`  version=${row.version}  name=${row.name}`);
    }
  }

  if (report.missing_from_prod.length > 0) {
    lines.push('');
    lines.push(`Missing from prod: ${report.missing_from_prod.join(', ')}`);
  }
  if (report.extra_vs_prod.length > 0) {
    lines.push('');
    lines.push(`Extra vs prod: ${report.extra_vs_prod.join(', ')}`);
  }

  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main (DB-connected)
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  const projectRef = args.projectRef ?? process.env.STAGING_PROJECT_REF;
  const serviceRoleKey = args.serviceRoleKey ?? process.env.SUPABASE_SERVICE_ROLE_KEY;
  const supabaseUrl = args.supabaseUrl
    ?? (projectRef ? `https://${projectRef}.supabase.co` : undefined);

  if (!supabaseUrl) {
    console.error('::error::Missing --project-ref / STAGING_PROJECT_REF or --supabase-url.');
    process.exit(1);
  }
  if (!serviceRoleKey) {
    console.error('::error::Missing --service-role-key / SUPABASE_SERVICE_ROLE_KEY.');
    process.exit(1);
  }

  const client = createClient(supabaseUrl, serviceRoleKey, {
    db: { schema: 'supabase_migrations' },
  });

  // Query migration rows.
  const { data: migrationData, error: migrationError } = await client
    .from('schema_migrations')
    .select('version, name')
    .order('version', { ascending: true });

  if (migrationError) {
    console.error(`::error::Failed to query schema_migrations: ${migrationError.message}`);
    process.exit(1);
  }

  const migrationRows: MigrationRow[] = (migrationData ?? []).map((r) => ({
    version: String(r.version),
    name: String(r.name),
  }));

  // Query SUBMITTED anchor count.
  const publicClient = createClient(supabaseUrl, serviceRoleKey);
  const { count, error: anchorError } = await publicClient
    .from('anchors')
    .select('*', { count: 'exact', head: true })
    .eq('status', 'SUBMITTED');

  if (anchorError) {
    console.error(`::error::Failed to query anchors: ${anchorError.message}`);
    process.exit(1);
  }

  const report = buildReport({
    projectRef: projectRef ?? supabaseUrl,
    migrationRows,
    submittedAnchorCount: count ?? 0,
    prodVersions: args.prodVersions,
  });

  if (args.format === 'text') {
    process.stdout.write(formatText(report));
  } else {
    console.log(JSON.stringify(report, null, 2));
  }

  const allPassed = report.checks.every((c) => c.passed);
  if (allPassed) {
    if (args.format !== 'json') {
      console.log('All checks passed — staging environment is clean.');
    }
  } else {
    process.exit(1);
  }
}

// ---------------------------------------------------------------------------
// Entry-point guard
// ---------------------------------------------------------------------------

function isMainModule(metaUrl: string, argvPath: string | undefined): boolean {
  return argvPath !== undefined && resolve(fileURLToPath(metaUrl)) === resolve(argvPath);
}

if (isMainModule(import.meta.url, process.argv[1])) {
  main().catch((err) => {
    console.error(`::error::Unexpected error: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  });
}
