#!/usr/bin/env -S npx tsx
/**
 * SCRUM-1668 addendum — staging-honesty preflight.
 *
 * Queries a Supabase staging database and reports whether the environment
 * is clean or has migration artifacts left over from prior PR soaks,
 * purges, or fixture seeding.
 *
 * Usage:
 *   npx tsx scripts/ci/staging-honesty-preflight.ts \
 *     --project-ref ujtlwnoqfhtitcmsnrpq \
 *     --format json
 *
 * Connection:
 *   --project-ref  Supabase project ref (or STAGING_PROJECT_REF env var).
 *                  URL derived as https://<ref>.supabase.co
 *   --prod-project-ref  Production Supabase project ref (or PROD_PROJECT_REF
 *                  env var). When paired with a Management API token, the
 *                  prod ledger and prod cron facts are queried live.
 *   --supabase-url Override the derived URL directly.
 *   --service-role-key  Service role key (or SUPABASE_SERVICE_ROLE_KEY env).
 *   --management-api-token  Supabase Management API token (or
 *                  SUPABASE_ACCESS_TOKEN / SUPABASE_MANAGEMENT_API_TOKEN env)
 *                  used as a read-only fallback when supabase_migrations is
 *                  hidden from PostgREST.
 *
 * Checks:
 *   1. PR-only / staging-only rows (timestamp versions, pr695_/pr697_/
 *      staging_purge_/staging_only_ prefixes)
 *   2. Duplicate migration names
 *   3. Duplicate migration versions
 *   4. Known artifact rows (hardcoded list)
 *   5. Missing SUBMITTED anchors
 *   6. Prod ledger divergence
 *   7. Org topology (single-tenant prod vs multi-org staging seeds)
 *   8. Prod facts (pg_cron vacuum-anchors, refresh_pipeline_dashboard_cache)
 *
 * Exit 0 = all checks pass (clean_mirror).
 * Exit 1 = at least one check failed.
 */

import { createClient } from '@supabase/supabase-js';
import { readdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface MigrationRow {
  version: string;
  name: string;
}

export interface ArtifactClassification {
  row: MigrationRow;
  reason: string;
}

export interface CheckResult {
  name: string;
  passed: boolean;
  details: string;
}

export type EnvironmentType = 'clean_mirror' | 'soak_artifact' | 'fixture_seeded';

export interface PreflightReport {
  environment_type: EnvironmentType;
  staging_project_ref: string;
  timestamp: string;
  checks: CheckResult[];
  artifact_rows: MigrationRow[];
  missing_from_staging: string[];
  extra_vs_prod: string[];
}

export interface OrgTopologyData {
  totalOrgs: number;
  seedOrgs: number;
}

/**
 * One row of the org-name projection used by Check 7.
 *
 * FD-PREFLIGHT-1: this used to be `{ name: string }`. `public.organizations`
 * has no `name` column — it has `legal_name` and `display_name` — so the
 * PostgREST select failed 42703 on every rig and Check 7 never ran.
 */
export interface OrgNameRow {
  legal_name: string | null;
  display_name: string | null;
}

export interface ProdFactsData {
  cronJobNames: string[];
  functionExists: boolean;
}

export interface ParsedArgs {
  projectRef: string | undefined;
  prodProjectRef: string | undefined;
  supabaseUrl: string | undefined;
  serviceRoleKey: string | undefined;
  managementApiToken: string | undefined;
  prodVersions: string[];
  prodFacts: ProdFactsData | undefined;
  format: 'json' | 'text';
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const CANONICAL_INIT_VERSION = '00000000000000';
const CANONICAL_INIT_NAMES = new Set([CANONICAL_INIT_VERSION, 'baseline_at_main_HEAD']);
const DEFAULT_PROD_VERSIONS = [CANONICAL_INIT_VERSION, '0294', '0295', '0296', '0297'];

/** Names that are categorically known artifacts from prior soak runs. */
const KNOWN_ARTIFACT_NAMES = new Set([
  'pr695_0292',
  'pr695_0293',
  'pr697_0290',
  'staging_purge_v5',
  'staging_purge_v6',
]);

/** Name that becomes an artifact only when it appears more than once. */
const KNOWN_DUPLICATE_NAME = '0294_refund_org_credit';

/**
 * Prefixes in migration names that indicate staging-only or PR-only rows.
 * Checked with `startsWith` against the lowercased name.
 */
const STAGING_NAME_PREFIXES = ['pr695_', 'pr697_', 'staging_purge_', 'staging_only_'];

/**
 * A version with 14+ digits is a Supabase timestamp migration (yyyyMMddHHmmss)
 * generated by preview branches or manual `supabase migration new`. These are
 * never canonical.
 *
 * Exception: '00000000000000' is the init row and always canonical.
 */
const TIMESTAMP_VERSION_RE = /^\d{14,}$/;

/** Prefixes in org names that indicate staging seed data (case-insensitive). */
const SEED_ORG_PREFIXES = ['stg', 'staging_seed_', 'test_org_'];

/**
 * The columns on `public.organizations` that can carry a staging seed marker.
 *
 * FD-PREFLIGHT-1: there is no `organizations.name`. Selecting it made Check 7
 * (`org_topology`) throw 42703 on every rig, and the caller-side guard turned
 * that into a silent skip. Keep this list in sync with the table; the unit
 * suite ratchets on both the list and the call site that uses it.
 */
export const ORG_NAME_COLUMNS = ['legal_name', 'display_name'] as const;

const MANAGEMENT_API_BASE_URL = 'https://api.supabase.com/v1';
const MANAGEMENT_API_TIMEOUT_MS = 30_000;
const MIGRATION_LEDGER_QUERY = `
  select version, name
  from supabase_migrations.schema_migrations
  order by version asc
`;
const MIGRATION_VERSION_QUERY = `
  select version
  from supabase_migrations.schema_migrations
  order by version asc
`;
const CRON_JOB_NAMES_QUERY = `
  select coalesce(jsonb_agg(jobname order by jobname), '[]'::jsonb) as cron_job_names
  from cron.job
`;
const REFRESH_FUNCTION_EXISTS_QUERY = `
  select to_regprocedure('public.refresh_pipeline_dashboard_cache()') is not null as function_exists
`;

// ---------------------------------------------------------------------------
// Pure classification functions (exported for testing)
// ---------------------------------------------------------------------------

/**
 * Classify a single migration row. Returns null if the row looks canonical,
 * or an ArtifactClassification describing why it is suspect.
 */
export function classifyMigrationRow(row: MigrationRow): ArtifactClassification | null {
  const { version, name } = row;

  // Only the canonical init/baseline rows get the init-version exemption.
  if (version === CANONICAL_INIT_VERSION && CANONICAL_INIT_NAMES.has(name)) return null;

  // Known staging/PR prefixes in name.
  const lowerName = name.toLowerCase();
  for (const prefix of STAGING_NAME_PREFIXES) {
    if (lowerName.startsWith(prefix)) {
      return { row, reason: `name starts with ${prefix}` };
    }
  }

  if (version === CANONICAL_INIT_VERSION) {
    return { row, reason: `init version (${version}) with non-canonical name (${name})` };
  }

  // Timestamp-format version (14+ digits, but not a canonical init row).
  if (TIMESTAMP_VERSION_RE.test(version)) {
    return { row, reason: `timestamp version (${version}) — likely preview-branch or staging-only` };
  }

  return null;
}

/**
 * Generic duplicate finder — returns values of `field` that appear more than once.
 */
function findDuplicates(rows: MigrationRow[], field: keyof MigrationRow): string[] {
  const counts = new Map<string, number>();
  for (const row of rows) {
    const val = row[field];
    counts.set(val, (counts.get(val) ?? 0) + 1);
  }
  return [...counts.entries()].filter(([, count]) => count > 1).map(([val]) => val);
}

/**
 * Reconstruct a canonical name identity for a ledger row so that two genuinely
 * distinct migrations whose stored `name` merely dropped its numeric prefix are
 * not mistaken for a duplicate.
 *
 * `supabase db push` records a migration's `name` WITHOUT its numeric prefix
 * (e.g. both `0302_validate_api_key_rpc_hardening` and
 * `0303_validate_api_key_rpc_hardening` collapse to the bare
 * `validate_api_key_rpc_hardening`), while keeping the distinct numeric
 * `version` (0302 vs 0303). Prod, by contrast, stores the prefixed name. Naively
 * counting bare names flags the two distinct migrations as a duplicate on a
 * legitimately-clean isolated rig.
 *
 * Identity rules:
 *  - If the stored `name` already carries a `NNNN_` numeric prefix, the name is
 *    authoritative and used verbatim. This preserves genuine-duplicate detection
 *    (two rows with the SAME prefixed name collide regardless of version) and
 *    keeps contamination signals (a prefixed name whose own prefix disagrees with
 *    its version still collides with the original under the shared prefixed name).
 *  - Otherwise the prefix was dropped on push, so reconstruct `${version}_${name}`
 *    — but only when the row's `version` is a real repo-backed numeric version
 *    (present in `repoVersions`). That guard means two distinct migrations whose
 *    bare names match are separated by their distinct repo-backed versions, while
 *    a non-repo/garbage version cannot manufacture a phantom-distinct identity to
 *    mask a real collision (it falls through to the bare name).
 */
function canonicalNameIdentity(row: MigrationRow, repoVersions?: ReadonlySet<string>): string {
  const { version, name } = row;

  // Name already carries its own numeric prefix → authoritative, use verbatim.
  if (/^\d{4,}_/.test(name)) return name;

  // Bare (prefix-dropped) name: reconstruct identity from the numeric version,
  // but only when that version is a real repo migration. Without a repo set, or
  // for a version the repo does not back, fall back to the bare name so genuine
  // collisions (and contamination) still surface.
  if (version && repoVersions?.has(version)) {
    return `${version}_${name}`;
  }

  return name;
}

/**
 * Find migration names that appear more than once.
 *
 * When `repoVersions` (the repo source-of-truth numeric versions) is supplied,
 * identity is normalized via {@link canonicalNameIdentity} so that two
 * genuinely-distinct migrations whose stored names merely dropped their numeric
 * prefix on `supabase db push` are NOT flagged — while same-version+same-name
 * replays and prefixed-name collisions still are. Returns the stored `name`(s)
 * whose canonical identity collides.
 *
 * Without `repoVersions`, behavior is the legacy bare-name count.
 */
export function findDuplicateNames(rows: MigrationRow[], repoVersions?: ReadonlySet<string>): string[] {
  if (!repoVersions) {
    return findDuplicates(rows, 'name');
  }

  // Count by canonical identity, but report the human-readable stored name.
  const identityCounts = new Map<string, number>();
  const identityToNames = new Map<string, Set<string>>();
  for (const row of rows) {
    const identity = canonicalNameIdentity(row, repoVersions);
    identityCounts.set(identity, (identityCounts.get(identity) ?? 0) + 1);
    let names = identityToNames.get(identity);
    if (!names) {
      names = new Set<string>();
      identityToNames.set(identity, names);
    }
    names.add(row.name);
  }

  const duplicates: string[] = [];
  for (const [identity, count] of identityCounts) {
    if (count > 1) {
      for (const name of identityToNames.get(identity) ?? []) {
        duplicates.push(name);
      }
    }
  }
  return duplicates;
}

/**
 * Find migration versions that appear more than once.
 */
export function findDuplicateVersions(rows: MigrationRow[]): string[] {
  return findDuplicates(rows, 'version');
}

/**
 * Detect rows that match the hardcoded known-artifact list.
 * Also flags duplicate occurrences of KNOWN_DUPLICATE_NAME.
 */
export function detectKnownArtifacts(rows: MigrationRow[]): MigrationRow[] {
  const artifacts: MigrationRow[] = [];

  // Track how many times the known-duplicate name appears.
  let duplicateNameCount = 0;

  for (const row of rows) {
    if (KNOWN_ARTIFACT_NAMES.has(row.name)) {
      artifacts.push(row);
      continue;
    }
    if (row.name === KNOWN_DUPLICATE_NAME) {
      duplicateNameCount++;
      if (duplicateNameCount > 1) {
        // Flag the second (and subsequent) occurrence.
        artifacts.push(row);
      }
    }
  }

  return artifacts;
}

export function isSupabaseMigrationsSchemaUnavailable(
  error: { code?: string; message?: string } | null | undefined,
): boolean {
  const code = error?.code?.toUpperCase();
  const message = error?.message?.toLowerCase() ?? '';
  return code === 'PGRST106'
    || message.includes('schema must be one of')
    || (message.includes('supabase_migrations') && message.includes('invalid schema'));
}

function normalizeMigrationVersion(value: unknown): string | null {
  if (value == null) return null;
  if (typeof value !== 'string' && typeof value !== 'number') return null;
  const raw = String(value).trim();
  if (!raw) return null;
  if (raw === CANONICAL_INIT_VERSION) return raw;
  // Supabase stores canonical short migrations as four-digit strings in prod.
  // Management API numeric rows such as 294 must compare as "0294".
  if (/^\d+$/.test(raw) && raw.length < 14) {
    return raw.padStart(4, '0');
  }
  return raw;
}

function normalizeMigrationName(value: unknown): string {
  if (value == null) return '';
  if (typeof value !== 'string' && typeof value !== 'number') return '';
  return String(value).trim();
}

export function mapManagementMigrationRows(rows: readonly Record<string, unknown>[]): MigrationRow[] {
  return rows.flatMap((row) => {
    const version = normalizeMigrationVersion(row.version);
    if (!version) return [];
    return [{
      version,
      name: normalizeMigrationName(row.name),
    }];
  });
}

export function mapManagementMigrationVersions(rows: readonly Record<string, unknown>[]): string[] {
  return rows.flatMap((row) => {
    const version = normalizeMigrationVersion(row.version);
    return version ? [version] : [];
  });
}

export function mapManagementProdFacts(
  cronRows: readonly Record<string, unknown>[],
  functionRows: readonly Record<string, unknown>[],
): ProdFactsData {
  const cronJobNamesValue = cronRows[0]?.cron_job_names;
  const cronJobNames = Array.isArray(cronJobNamesValue)
    ? cronJobNamesValue.map(String)
    : [];
  return {
    cronJobNames,
    functionExists: isTruthyManagementValue(functionRows[0]?.function_exists),
  };
}

function isTruthyManagementValue(value: unknown): boolean {
  return value === true || value === 'true' || value === 't' || value === '1' || value === 1;
}

/**
 * Compare staging migration versions against the prod ledger.
 */
export function computeProdDivergence(
  rows: MigrationRow[],
  prodVersions: string[],
): { missingFromStaging: string[]; extraVsProd: string[] } {
  const stagingVersions = new Set(rows.map((r) => r.version));
  const prodSet = new Set(prodVersions);

  const missingFromStaging = prodVersions.filter((v) => !stagingVersions.has(v));
  const extraVsProd = [...stagingVersions].filter((v) => !prodSet.has(v));

  return { missingFromStaging, extraVsProd };
}

/**
 * Parse the canonical migration version (the `NNNN_` prefix, or the all-zero
 * baseline prefix) from a migration filename. Mirrors the convention enforced
 * by scripts/ci/check-migration-prefix-uniqueness.ts so the preflight reads the
 * repo the same way the rest of CI does.
 *
 * Returns null for files that carry no numeric prefix (templates, READMEs).
 */
export function parseRepoMigrationVersion(filename: string): string | null {
  // Strip any leading directory component, then match a leading 4+-digit prefix.
  const base = filename.split('/').pop() ?? filename;
  const m = base.match(/^(\d{4,})_/);
  return m ? m[1] : null;
}

/**
 * True when the ledger contains the canonical squashed-baseline row. The
 * baseline row is recognised by EITHER its version or its name matching the
 * canonical init/baseline set (the squash records version `00000000000000`
 * with name `baseline_at_main_HEAD`).
 *
 * Presence of this row means the rig was built from a squashed baseline, so the
 * baseline legitimately subsumes all pre-baseline prod history — those prod rows
 * being "missing" from the rig is expected, not contamination.
 */
export function hasCanonicalBaseline(rows: MigrationRow[]): boolean {
  return rows.some((r) => CANONICAL_INIT_NAMES.has(r.version) || CANONICAL_INIT_NAMES.has(r.name));
}

/**
 * Structured verdict from the repo-files-as-source-of-truth divergence analysis.
 */
export interface ProdDivergenceVerdict {
  /** Rig carries the canonical squashed-baseline row. */
  baselinePresent: boolean;
  /** Rig versions absent from prod AND absent from the repo (potential contamination). MUST FAIL. */
  unexplainedExtras: string[];
  /** Repo migration versions absent from the rig ledger (rig incomplete / behind main). MUST FAIL. */
  missingRepoMigrations: string[];
  /** Prod versions absent from the rig (informational under a baseline squash; failure otherwise). */
  prodMissing: string[];
  /** Overall pass/fail for the prod_divergence check. */
  passed: boolean;
}

/**
 * Baseline-squash-aware divergence analysis.
 *
 * Legitimacy is judged against the repo migration files (the source of truth
 * per §1.2 schema-first) plus the canonical baseline — NEVER the rig's own
 * claims. A clean isolated rig built by squashing pre-baseline history into the
 * canonical baseline and then applying every repo migration is `clean_mirror`,
 * even though its ledger diverges from prod's (prod still carries pre-baseline
 * rows and stores recent migrations under timestamp/descriptive version
 * strings).
 *
 * Buckets (compared by version):
 *  - unexplainedExtras: rig ∉ prod AND rig ∉ repo AND not the canonical baseline.
 *    These are rows nothing in the repo or prod can account for → contamination.
 *  - missingRepoMigrations: repo ∉ rig → the rig is behind the repo / incomplete.
 *  - prodMissing: prod ∉ rig. Informational when a baseline row is present (the
 *    baseline subsumes pre-baseline history); otherwise a failure (this preserves
 *    the old strictness for incremental shared-staging ledgers with no baseline).
 *
 * PASS iff unexplainedExtras and missingRepoMigrations are both empty AND
 * (a baseline is present OR there are no prod-missing rows).
 */
export function analyzeProdDivergence(
  rows: MigrationRow[],
  prodVersions: string[],
  repoVersions: ReadonlySet<string>,
): ProdDivergenceVerdict {
  const rigVersions = new Set(rows.map((r) => r.version));
  const prodSet = new Set(prodVersions);
  const baselinePresent = hasCanonicalBaseline(rows);

  // Rig rows that prod does not have.
  const extras = [...rigVersions].filter((v) => !prodSet.has(v));

  // An extra is "explained" if it corresponds to a repo migration file or is the
  // canonical baseline version. Anything else is unaccounted-for → contamination.
  const unexplainedExtras = extras.filter(
    (v) => !repoVersions.has(v) && !CANONICAL_INIT_NAMES.has(v),
  );

  // Every repo migration must be present in the rig ledger.
  const missingRepoMigrations = [...repoVersions].filter((v) => !rigVersions.has(v));

  // Prod versions the rig lacks.
  const prodMissing = prodVersions.filter((v) => !rigVersions.has(v));

  const passed =
    unexplainedExtras.length === 0 &&
    missingRepoMigrations.length === 0 &&
    (baselinePresent || prodMissing.length === 0);

  return { baselinePresent, unexplainedExtras, missingRepoMigrations, prodMissing, passed };
}

/**
 * Check org topology: distinguish single-tenant prod from multi-org staging seeds.
 * Requires org-scoped fixtures (non-seed orgs) when seed orgs are present.
 */
export function checkOrgTopology(data: OrgTopologyData): CheckResult {
  if (data.totalOrgs === 0) {
    return {
      name: 'org_topology',
      passed: false,
      details: 'No organizations found — staging lacks seed data.',
    };
  }

  if (data.seedOrgs === 0) {
    return {
      name: 'org_topology',
      passed: true,
      details: `${data.totalOrgs} org(s), no staging seed orgs — prod-like single-tenant topology.`,
    };
  }

  const fixtureOrgs = data.totalOrgs - data.seedOrgs;
  if (fixtureOrgs > 0) {
    return {
      name: 'org_topology',
      passed: true,
      details: `${data.totalOrgs} org(s) total (${data.seedOrgs} seed, ${fixtureOrgs} org-scoped fixture(s)).`,
    };
  }

  return {
    name: 'org_topology',
    passed: false,
    details: `All ${data.totalOrgs} org(s) are seed-prefixed — no org-scoped fixtures for connector work.`,
  };
}

/**
 * Verify prod facts from the 2026-05-06 correction:
 *   - pg_cron has vacuum-anchors job
 *   - refresh_pipeline_dashboard_cache() exists
 *   - refresh-pipeline-dashboard-cache is scheduled per the SCRUM-1708 cadence
 */
export function checkProdFacts(data: ProdFactsData): CheckResult {
  const issues: string[] = [];

  if (!data.cronJobNames.includes('vacuum-anchors')) {
    issues.push('pg_cron vacuum-anchors job missing');
  }

  if (!data.functionExists) {
    issues.push('refresh_pipeline_dashboard_cache() function missing');
  }

  if (!data.cronJobNames.includes('refresh-pipeline-dashboard-cache')) {
    issues.push('refresh-pipeline-dashboard-cache job missing');
  }

  return {
    name: 'prod_facts',
    passed: issues.length === 0,
    details: issues.length === 0
      ? 'Prod facts verified: vacuum-anchors scheduled, refresh_pipeline_dashboard_cache exists, refresh-pipeline-dashboard-cache scheduled.'
      : `Prod facts divergence: ${issues.join('; ')}.`,
  };
}

/**
 * Classify an org name as a staging seed org (case-insensitive prefix match).
 */
export function isOrgSeedName(name: string): boolean {
  const lower = name.toLowerCase();
  return SEED_ORG_PREFIXES.some((p) => lower.startsWith(p));
}

/**
 * True when EITHER org-name column carries a staging seed prefix.
 *
 * Both columns are considered because a rig can be seeded with a real-looking
 * `legal_name` and a `stg`-prefixed `display_name`, or the reverse.
 */
export function isOrgRowSeeded(row: OrgNameRow): boolean {
  return ORG_NAME_COLUMNS.some((column) => {
    const value = row[column];
    return typeof value === 'string' && isOrgSeedName(value);
  });
}

/**
 * Check 7 could not be evaluated — report it as a FAILURE.
 *
 * FD-PREFLIGHT-1. A preflight whose whole job is to refuse to vouch for a rig
 * must never treat "I could not look" as "I looked and it was fine". If the
 * organizations projection cannot be read, the environment is not certified
 * clean; it is uncertified, and that is a failing outcome.
 */
export function checkOrgTopologyUnavailable(reason: string): CheckResult {
  return {
    name: 'org_topology',
    passed: false,
    details:
      `org_topology could not be evaluated: ${reason}. ` +
      'A check that cannot run is a FAILED check, not a skipped one — ' +
      'this environment is uncertified for merge-grade soak evidence.',
  };
}

// ---------------------------------------------------------------------------
// Report builder
// ---------------------------------------------------------------------------

/**
 * Check 6 (`prod_divergence`) as a standalone verdict.
 *
 * Split out of buildReport so the report builder stays readable: the
 * baseline-squash-aware path and the legacy strict path are two different
 * judgements that happen to share a check name.
 */
function buildProdDivergenceCheck(
  migrationRows: MigrationRow[],
  prodVersions: string[],
  repoVersions: ReadonlySet<string> | undefined,
  divergence: { missingFromStaging: string[]; extraVsProd: string[] },
): CheckResult {
  if (!repoVersions) {
    const prodDiverged =
      divergence.missingFromStaging.length > 0 || divergence.extraVsProd.length > 0;
    return {
      name: 'prod_divergence',
      passed: !prodDiverged,
      details: prodDiverged
        ? `Missing from staging: [${divergence.missingFromStaging.join(', ')}]; Extra vs prod: [${divergence.extraVsProd.join(', ')}]`
        : 'Staging versions match prod ledger.',
    };
  }

  const verdict = analyzeProdDivergence(migrationRows, prodVersions, repoVersions);
  if (verdict.passed) {
    const subsumed =
      verdict.baselinePresent && verdict.prodMissing.length > 0
        ? ` ${verdict.prodMissing.length} pre-baseline/version-shape prod row(s) subsumed by the canonical baseline (informational).`
        : '';
    return {
      name: 'prod_divergence',
      passed: true,
      details: `Rig ledger reconciles with repo migration files + canonical baseline.${subsumed}`,
    };
  }

  const detailParts: string[] = [];
  if (verdict.unexplainedExtras.length > 0) {
    detailParts.push(`Unexplained extras (not in repo or prod): [${verdict.unexplainedExtras.join(', ')}]`);
  }
  if (verdict.missingRepoMigrations.length > 0) {
    detailParts.push(`Repo migrations missing from rig: [${verdict.missingRepoMigrations.join(', ')}]`);
  }
  if (!verdict.baselinePresent && verdict.prodMissing.length > 0) {
    detailParts.push(`Prod versions missing from rig (no baseline to subsume them): [${verdict.prodMissing.join(', ')}]`);
  }
  return { name: 'prod_divergence', passed: false, details: detailParts.join('; ') };
}

export function buildReport(opts: {
  projectRef: string;
  migrationRows: MigrationRow[];
  submittedAnchorCount: number;
  prodVersions: string[];
  /**
   * Canonical migration versions parsed from supabase/migrations/*.sql (the
   * repo source of truth). When provided, the prod_divergence check becomes
   * baseline-squash-aware via analyzeProdDivergence. When omitted, the legacy
   * strict computeProdDivergence behavior is preserved (any divergence fails).
   */
  repoVersions?: ReadonlySet<string>;
  orgTopology?: OrgTopologyData;
  /**
   * Why the org-topology projection could not be read. When set (and
   * `orgTopology` is not), Check 7 is emitted as a FAILURE rather than
   * omitted — see checkOrgTopologyUnavailable / FD-PREFLIGHT-1.
   */
  orgTopologyError?: string;
  prodFacts?: ProdFactsData;
}): PreflightReport {
  const { projectRef, migrationRows, submittedAnchorCount, prodVersions, repoVersions } = opts;
  const checks: CheckResult[] = [];
  let allArtifactRows: MigrationRow[] = [];

  // Check 1: PR-only / staging-only rows
  const classified = migrationRows
    .map((row) => classifyMigrationRow(row))
    .filter((c): c is ArtifactClassification => c !== null);
  const artifactRowsFromClassification = classified.map((c) => c.row);
  checks.push({
    name: 'staging_only_rows',
    passed: classified.length === 0,
    details: classified.length === 0
      ? 'No PR-only or staging-only migration rows found.'
      : `${classified.length} suspect row(s): ${classified.map((c) => `${c.row.name} (${c.reason})`).join('; ')}`,
  });

  // Check 2: Duplicate names.
  // When repo migration versions are supplied, normalize identity by the numeric
  // version prefix: `supabase db push` stores a rig's names WITHOUT their numeric
  // prefix, so two genuinely-distinct migrations (e.g. 0302 and 0303 of the same
  // descriptive name) collapse to one repeated bare name on the rig. Those are NOT
  // a duplicate. Same-version+same-name replays and prefixed-name collisions are
  // still flagged. Without repoVersions, the legacy bare-name count applies.
  const dupeNames = findDuplicateNames(migrationRows, repoVersions);
  checks.push({
    name: 'duplicate_names',
    passed: dupeNames.length === 0,
    details: dupeNames.length === 0
      ? 'No duplicate migration names.'
      : `Duplicate name(s): ${dupeNames.join(', ')}`,
  });

  // Check 3: Duplicate versions
  const dupeVersions = findDuplicateVersions(migrationRows);
  checks.push({
    name: 'duplicate_versions',
    passed: dupeVersions.length === 0,
    details: dupeVersions.length === 0
      ? 'No duplicate migration versions.'
      : `Duplicate version(s): ${dupeVersions.join(', ')}`,
  });

  // Check 4: Known artifact rows
  const knownArtifacts = detectKnownArtifacts(migrationRows);
  checks.push({
    name: 'known_artifacts',
    passed: knownArtifacts.length === 0,
    details: knownArtifacts.length === 0
      ? 'No known artifact rows.'
      : `${knownArtifacts.length} known artifact(s): ${knownArtifacts.map((r) => r.name).join(', ')}`,
  });

  // Check 5: Missing SUBMITTED anchors
  checks.push({
    name: 'submitted_anchors',
    passed: submittedAnchorCount > 0,
    details: submittedAnchorCount > 0
      ? `${submittedAnchorCount} SUBMITTED anchor(s) found.`
      : 'Zero SUBMITTED anchors — environment may lack test fixtures.',
  });

  // Check 6: Prod divergence.
  // The raw buckets (missingFromStaging / extraVsProd) are always reported for
  // transparency. When the repo migration files are supplied, the PASS/FAIL
  // verdict is baseline-squash-aware (analyzeProdDivergence): legitimacy is
  // judged against repo files + the canonical baseline, never the rig's own
  // claims. Without repoVersions, the legacy strict rule applies (any
  // divergence fails) — this preserves shared-staging behavior.
  const divergence = computeProdDivergence(migrationRows, prodVersions);
  checks.push(
    buildProdDivergenceCheck(migrationRows, prodVersions, repoVersions, divergence),
  );

  // Check 7: Org topology (single-tenant prod vs multi-org staging seeds).
  // An unreadable projection is a FAILED check, never an omitted one.
  if (opts.orgTopology) {
    checks.push(checkOrgTopology(opts.orgTopology));
  } else if (opts.orgTopologyError) {
    checks.push(checkOrgTopologyUnavailable(opts.orgTopologyError));
  }

  // Check 8: Prod facts (pg_cron, function existence, scheduling)
  if (opts.prodFacts) {
    checks.push(checkProdFacts(opts.prodFacts));
  }

  // Collect all artifact rows (deduplicated by version+name).
  const seen = new Set<string>();
  allArtifactRows = [
    ...artifactRowsFromClassification,
    ...knownArtifacts,
  ].filter((row) => {
    const key = `${row.version}::${row.name}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  // Determine environment type.
  const anyFailed = checks.some((c) => !c.passed);
  const hasArtifacts = allArtifactRows.length > 0
    || dupeNames.length > 0
    || dupeVersions.length > 0
    || classified.length > 0;
  const missingAnchors = submittedAnchorCount === 0;

  let environmentType: EnvironmentType;
  if (!anyFailed) {
    environmentType = 'clean_mirror';
  } else if (hasArtifacts) {
    environmentType = 'soak_artifact';
  } else if (missingAnchors) {
    environmentType = 'fixture_seeded';
  } else {
    // Prod divergence only, no artifacts — still classify as soak_artifact.
    environmentType = 'soak_artifact';
  }

  return {
    environment_type: environmentType,
    staging_project_ref: projectRef,
    timestamp: new Date().toISOString(),
    checks,
    artifact_rows: allArtifactRows,
    missing_from_staging: divergence.missingFromStaging,
    extra_vs_prod: divergence.extraVsProd,
  };
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

export function parseArgs(argv: string[]): ParsedArgs {
  let projectRef: string | undefined;
  let prodProjectRef: string | undefined;
  let supabaseUrl: string | undefined;
  let serviceRoleKey: string | undefined;
  let managementApiToken: string | undefined;
  let prodVersions: string[] = DEFAULT_PROD_VERSIONS;
  let prodFacts: ProdFactsData | undefined;
  let format: 'json' | 'text' = 'json';

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = argv[i + 1];
    switch (arg) {
      case '--project-ref':
        projectRef = next;
        i++;
        break;
      case '--prod-project-ref':
        prodProjectRef = next;
        i++;
        break;
      case '--supabase-url':
        supabaseUrl = next;
        i++;
        break;
      case '--service-role-key':
        serviceRoleKey = next;
        i++;
        break;
      case '--management-api-token':
        managementApiToken = next;
        i++;
        break;
      case '--prod-versions':
        prodVersions = next?.split(',').map((v) => v.trim()).filter(Boolean) ?? DEFAULT_PROD_VERSIONS;
        i++;
        break;
      case '--prod-facts':
        try {
          prodFacts = JSON.parse(next) as ProdFactsData;
        } catch { /* ignore malformed JSON */ }
        i++;
        break;
      case '--format':
        format = next === 'text' ? 'text' : 'json';
        i++;
        break;
    }
  }

  return { projectRef, prodProjectRef, supabaseUrl, serviceRoleKey, managementApiToken, prodVersions, prodFacts, format };
}

// ---------------------------------------------------------------------------
// Text formatter
// ---------------------------------------------------------------------------

function formatText(report: PreflightReport): string {
  const lines: string[] = [];
  lines.push('='.repeat(60));
  lines.push(`Staging Honesty Preflight — ${report.environment_type.toUpperCase()}`);
  lines.push(`Project: ${report.staging_project_ref}`);
  lines.push(`Time:    ${report.timestamp}`);
  lines.push('='.repeat(60));
  lines.push('');

  for (const check of report.checks) {
    const icon = check.passed ? '[PASS]' : '[FAIL]';
    lines.push(`${icon} ${check.name}`);
    lines.push(`       ${check.details}`);
  }

  if (report.artifact_rows.length > 0) {
    lines.push('');
    lines.push('Artifact rows:');
    for (const row of report.artifact_rows) {
      lines.push(`  version=${row.version}  name=${row.name}`);
    }
  }

  if (report.missing_from_staging.length > 0) {
    lines.push('');
    lines.push(`Missing from staging: ${report.missing_from_staging.join(', ')}`);
  }
  if (report.extra_vs_prod.length > 0) {
    lines.push('');
    lines.push(`Extra vs prod: ${report.extra_vs_prod.join(', ')}`);
  }

  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main (DB-connected)
// ---------------------------------------------------------------------------

export async function queryManagementApi(projectRef: string, managementApiToken: string, query: string): Promise<Record<string, unknown>[]> {
  const response = await fetch(`${MANAGEMENT_API_BASE_URL}/projects/${encodeURIComponent(projectRef)}/database/query/read-only`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${managementApiToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query }),
    signal: AbortSignal.timeout(MANAGEMENT_API_TIMEOUT_MS),
  });

  if (!response.ok) {
    throw new Error(`Supabase Management API query failed (${response.status})`);
  }

  const payload = await response.json() as unknown;
  if (!Array.isArray(payload)) {
    throw new Error('Supabase Management API query returned a non-array payload.');
  }
  return payload.filter((row): row is Record<string, unknown> => row !== null && typeof row === 'object' && !Array.isArray(row));
}

async function fetchMigrationRowsViaManagementApi(projectRef: string, managementApiToken: string): Promise<MigrationRow[]> {
  const rows = await queryManagementApi(projectRef, managementApiToken, MIGRATION_LEDGER_QUERY);
  return mapManagementMigrationRows(rows);
}

async function fetchMigrationVersionsViaManagementApi(projectRef: string, managementApiToken: string): Promise<string[]> {
  const rows = await queryManagementApi(projectRef, managementApiToken, MIGRATION_VERSION_QUERY);
  return mapManagementMigrationVersions(rows);
}

async function fetchProdFactsViaManagementApi(projectRef: string, managementApiToken: string): Promise<ProdFactsData> {
  const [cronRows, functionRows] = await Promise.all([
    queryManagementApi(projectRef, managementApiToken, CRON_JOB_NAMES_QUERY),
    queryManagementApi(projectRef, managementApiToken, REFRESH_FUNCTION_EXISTS_QUERY),
  ]);
  return mapManagementProdFacts(cronRows, functionRows);
}

/**
 * Read the canonical migration versions from supabase/migrations/*.sql.
 * This is the repo source of truth the divergence verdict reconciles against.
 * Returns undefined (so buildReport falls back to legacy strictness) if the
 * directory cannot be read.
 */
function loadRepoMigrationVersions(): ReadonlySet<string> | undefined {
  const migrationsDir = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', 'supabase', 'migrations');
  try {
    const versions = new Set<string>();
    for (const file of readdirSync(migrationsDir)) {
      if (!file.endsWith('.sql') || file.startsWith('_')) continue;
      const version = parseRepoMigrationVersion(file);
      if (version) versions.add(version);
    }
    return versions.size > 0 ? versions : undefined;
  } catch {
    return undefined;
  }
}

/**
 * The narrow slice of a Supabase client queryOrgTopology needs. Structural, so
 * the helper does not have to name supabase-js's generic client type — which
 * varies with the schema type parameters and does not unify across call sites.
 */
interface OrgProjectionReader {
  from(table: string): {
    select(columns: string): PromiseLike<{
      data: unknown;
      error: { message: string } | null;
    }>;
  };
}

/**
 * Check 7's data, or the reason it could not be read.
 *
 * FD-PREFLIGHT-1: this used to select a column `organizations.name` that does
 * not exist. PostgREST answered 42703, the caller's `if (!error && data)` guard
 * fell through with no else, and the check silently disappeared from the report
 * — for every rig, indefinitely. Every branch here now yields either data or a
 * reason, and the caller turns a reason into a FAILED check.
 */
async function queryOrgTopology(
  publicClient: OrgProjectionReader,
): Promise<{ orgTopology?: OrgTopologyData; orgTopologyError?: string }> {
  try {
    const { data, error } = await publicClient
      .from('organizations')
      .select(ORG_NAME_COLUMNS.join(','));
    if (error) return { orgTopologyError: error.message };
    if (!data) return { orgTopologyError: 'organizations projection returned no rows payload.' };
    const rows = data as unknown as OrgNameRow[];
    return { orgTopology: { totalOrgs: rows.length, seedOrgs: rows.filter(isOrgRowSeeded).length } };
  } catch (err) {
    return { orgTopologyError: err instanceof Error ? err.message : String(err) };
  }
}

/**
 * Check 8 fallback: read pg_cron jobs from the environment under test when no
 * prod ref + Management API token were supplied. Returns undefined when the
 * `cron` schema is not exposed via PostgREST, which is the common case and is
 * why Check 8 stays optional (unlike Check 7 — see queryOrgTopology).
 */
async function queryCronFactsFromEnvironment(
  supabaseUrl: string,
  serviceRoleKey: string,
): Promise<ProdFactsData | undefined> {
  try {
    const cronClient = createClient(supabaseUrl, serviceRoleKey, { db: { schema: 'cron' } });
    const { data, error } = await cronClient.from('job').select('jobname');
    if (error || !data) return undefined;
    const cronJobNames = data.map((j: { jobname: string }) => j.jobname);
    return { cronJobNames, functionExists: cronJobNames.length > 0 };
  } catch {
    return undefined;
  }
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  const projectRef = args.projectRef ?? process.env.STAGING_PROJECT_REF;
  const prodProjectRef = args.prodProjectRef ?? process.env.PROD_PROJECT_REF;
  const serviceRoleKey = args.serviceRoleKey ?? process.env.SUPABASE_SERVICE_ROLE_KEY;
  const managementApiToken = args.managementApiToken
    ?? process.env.SUPABASE_ACCESS_TOKEN
    ?? process.env.SUPABASE_MANAGEMENT_API_TOKEN;
  const supabaseUrl = args.supabaseUrl
    ?? (projectRef ? `https://${projectRef}.supabase.co` : undefined);

  if (!supabaseUrl) {
    console.error('::error::Missing --project-ref / STAGING_PROJECT_REF or --supabase-url.');
    process.exit(1);
  }
  if (!serviceRoleKey) {
    console.error('::error::Missing --service-role-key / SUPABASE_SERVICE_ROLE_KEY.');
    process.exit(1);
  }

  const client = createClient(supabaseUrl, serviceRoleKey, {
    db: { schema: 'supabase_migrations' },
  });

  // Query migration rows.
  const { data: migrationData, error: migrationError } = await client
    .from('schema_migrations')
    .select('version, name')
    .order('version', { ascending: true });

  let migrationRows: MigrationRow[];
  if (migrationError) {
    if (isSupabaseMigrationsSchemaUnavailable(migrationError) && managementApiToken && projectRef) {
      migrationRows = await fetchMigrationRowsViaManagementApi(projectRef, managementApiToken);
    } else {
      const hint = isSupabaseMigrationsSchemaUnavailable(migrationError)
        ? ' Set --management-api-token or SUPABASE_ACCESS_TOKEN to query the ledger through the Supabase Management API.'
        : '';
      console.error(`::error::Failed to query schema_migrations: ${migrationError.message}${hint}`);
      process.exit(1);
    }
  } else {
    migrationRows = mapManagementMigrationRows(migrationData ?? []);
  }

  // Query SUBMITTED anchor count.
  const publicClient = createClient(supabaseUrl, serviceRoleKey);
  const { count, error: anchorError } = await publicClient
    .from('anchors')
    .select('*', { count: 'exact', head: true })
    .eq('status', 'SUBMITTED');

  if (anchorError) {
    console.error(`::error::Failed to query anchors: ${anchorError.message}`);
    process.exit(1);
  }

  // Check 7. Every failure path records a reason, so the check is reported as
  // FAILED instead of vanishing from the report — FD-PREFLIGHT-1.
  const { orgTopology, orgTopologyError } = await queryOrgTopology(publicClient);

  let prodVersions = args.prodVersions;
  if (managementApiToken && prodProjectRef) {
    try {
      prodVersions = await fetchMigrationVersionsViaManagementApi(prodProjectRef, managementApiToken);
    } catch {
      console.error('::error::Failed to query prod migration ledger via Management API; refusing to use configured/default prod versions as live prod evidence.');
      process.exit(1);
    }
  }

  // Prod facts: prefer CLI flag, then prod Management API, then environment cron schema.
  let prodFacts: ProdFactsData | undefined = args.prodFacts;
  if (!prodFacts && managementApiToken && prodProjectRef) {
    try {
      prodFacts = await fetchProdFactsViaManagementApi(prodProjectRef, managementApiToken);
    } catch {
      console.error('::error::Failed to query prod facts via Management API; refusing to use staging cron data as prod evidence.');
      process.exit(1);
    }
  }
  if (!prodFacts && !(managementApiToken && prodProjectRef)) {
    prodFacts = await queryCronFactsFromEnvironment(supabaseUrl, serviceRoleKey);
  }

  const repoVersions = loadRepoMigrationVersions();

  const report = buildReport({
    projectRef: projectRef ?? supabaseUrl,
    migrationRows,
    submittedAnchorCount: count ?? 0,
    prodVersions,
    repoVersions,
    orgTopology,
    orgTopologyError,
    prodFacts,
  });

  if (args.format === 'text') {
    process.stdout.write(formatText(report));
  } else {
    console.log(JSON.stringify(report, null, 2));
  }

  const allPassed = report.checks.every((c) => c.passed);
  if (allPassed) {
    if (args.format !== 'json') {
      console.log('All checks passed — staging environment is clean.');
    }
  } else {
    process.exit(1);
  }
}

// ---------------------------------------------------------------------------
// Entry-point guard
// ---------------------------------------------------------------------------

function isMainModule(metaUrl: string, argvPath: string | undefined): boolean {
  return argvPath !== undefined && resolve(fileURLToPath(metaUrl)) === resolve(argvPath);
}

if (isMainModule(import.meta.url, process.argv[1])) {
  main().catch((err) => {
    console.error(`::error::Unexpected error: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  });
}
