/**
 * Issue Credential Form
 *
 * Dialog for ORG_ADMIN users to issue credentials with
 * credential_type, label, and metadata. Reuses FileUpload
 * for document fingerprinting.
 *
 * Enhanced success screen (UF-04): shows verification URL, copy link,
 * and "anchoring in progress" messaging instead of closing immediately.
 *
 * @see P5-TS-05, UF-04
 */

import { useState, useCallback } from 'react';
import {
  Shield,
  Loader2,
  Award,
  CheckCircle,
  Copy,
  Check,
  ExternalLink,
  Plus,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { FileUpload } from '@/components/anchor/FileUpload';
import { supabase } from '@/lib/supabase';
import { validateAnchorCreate, CREDENTIAL_TYPES } from '@/lib/validators';
import { logAuditEvent } from '@/lib/auditLog';
import { useAuth } from '@/hooks/useAuth';
import { useProfile } from '@/hooks/useProfile';
import {
  FORM_LABELS,
  CREDENTIAL_TYPE_LABELS,
  TOAST,
  ANCHORING_STATUS_LABELS,
  ISSUE_CREDENTIAL_LABELS,
} from '@/lib/copy';
import { toast } from 'sonner';
import { verifyPath, recordDetailPath } from '@/lib/routes';
import { useNavigate } from 'react-router-dom';
import type { CredentialType } from '@/lib/validators';

interface IssueCredentialFormProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: () => void;
}

type Step = 'form' | 'success';

interface CreatedAnchor {
  id: string;
  publicId: string;
}

export function IssueCredentialForm({
  open,
  onOpenChange,
  onSuccess,
}: Readonly<IssueCredentialFormProps>) {
  const { user } = useAuth();
  const { profile } = useProfile();
  const navigate = useNavigate();

  const [step, setStep] = useState<Step>('form');
  const [file, setFile] = useState<File | null>(null);
  const [fingerprint, setFingerprint] = useState<string | null>(null);
  const [credentialType, setCredentialType] = useState<CredentialType | ''>('');
  const [label, setLabel] = useState('');
  const [issuedAt, setIssuedAt] = useState('');
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [createdAnchor, setCreatedAnchor] = useState<CreatedAnchor | null>(null);
  const [linkCopied, setLinkCopied] = useState(false);

  const handleFileSelect = useCallback((f: File, fp: string) => {
    setFile(f);
    setFingerprint(fp);
    setError(null);
  }, []);

  const resetForm = useCallback(() => {
    setStep('form');
    setFile(null);
    setFingerprint(null);
    setCredentialType('');
    setLabel('');
    setIssuedAt('');
    setCreating(false);
    setError(null);
    setCreatedAnchor(null);
    setLinkCopied(false);
  }, []);

  const handleClose = useCallback(() => {
    if (!creating) {
      resetForm();
      onOpenChange(false);
    }
  }, [creating, resetForm, onOpenChange]);

  const handleSubmit = useCallback(async () => {
    if (!file || !fingerprint || !user || !credentialType) return;

    setCreating(true);
    setError(null);

    try {
      const validated = validateAnchorCreate({
        fingerprint,
        filename: file.name,
        file_size: file.size,
        file_mime: file.type || null,
        org_id: profile?.org_id || null,
        credential_type: credentialType,
        label: label.trim() || null,
        metadata: issuedAt
          ? { issued_at: `${issuedAt}T00:00:00Z` }
          : null,
      });

      const { data: inserted, error: insertError } = await supabase
        .from('anchors')
        .insert({
          ...validated,
          user_id: user.id,
        })
        .select('id, public_id')
        .single();

      if (insertError) throw insertError;

      setCreatedAnchor({
        id: inserted.id,
        // public_id is auto-generated by trigger (migration 0037) — always non-null after insert
        publicId: inserted.public_id!,
      });

      logAuditEvent({
        eventType: 'CREDENTIAL_ISSUED',
        eventCategory: 'ANCHOR',
        targetType: 'anchor',
        targetId: inserted.id,
        orgId: profile?.org_id,
        details: `Issued ${credentialType} credential for "${file.name}"`,
      });

      toast.success(TOAST.CREDENTIAL_ISSUED);
      setStep('success');
      onSuccess?.();
    } catch (err) {
      if (err instanceof Error && err.name === 'ZodError') {
        const zodErr = err as import('zod').ZodError;
        setError(zodErr.issues.map((i) => i.message).join('; '));
      } else {
        setError(
          err instanceof Error ? err.message : 'Failed to issue credential'
        );
      }
      toast.error(TOAST.CREDENTIAL_ISSUE_FAILED);
    } finally {
      setCreating(false);
    }
  }, [
    file,
    fingerprint,
    user,
    profile,
    credentialType,
    label,
    issuedAt,
    onSuccess,
  ]);

  const handleCopyLink = useCallback(async () => {
    if (!createdAnchor) return;
    const baseUrl = import.meta.env.VITE_APP_URL || location.origin;
    const url = `${baseUrl}${verifyPath(createdAnchor.publicId)}`;
    await navigator.clipboard.writeText(url);
    setLinkCopied(true);
    toast.success(ANCHORING_STATUS_LABELS.LINK_COPIED);
    setTimeout(() => setLinkCopied(false), 2000);
  }, [createdAnchor]);

  const handleViewRecord = useCallback(() => {
    if (!createdAnchor) return;
    handleClose();
    navigate(recordDetailPath(createdAnchor.id));
  }, [createdAnchor, handleClose, navigate]);

  const handleIssueAnother = useCallback(() => {
    resetForm();
  }, [resetForm]);

  const canSubmit = !!file && !!fingerprint && !!credentialType && !creating;

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Award className="h-5 w-5 text-primary" />
            {ISSUE_CREDENTIAL_LABELS.TITLE}
          </DialogTitle>
          <DialogDescription>
            {step === 'form'
              ? ISSUE_CREDENTIAL_LABELS.DESCRIPTION
              : ANCHORING_STATUS_LABELS.SUCCESS_SUBTITLE}
          </DialogDescription>
        </DialogHeader>

        {step === 'form' && (
          <>
            <div className="space-y-4 py-2">
              {/* File upload */}
              <FileUpload onFileSelect={handleFileSelect} disabled={creating} />

              {/* Credential type */}
              <div className="space-y-2">
                <Label htmlFor="credential-type">
                  {FORM_LABELS.CREDENTIAL_TYPE}
                </Label>
                <Select
                  value={credentialType}
                  onValueChange={(v) => setCredentialType(v as CredentialType)}
                  disabled={creating}
                >
                  <SelectTrigger id="credential-type">
                    <SelectValue
                      placeholder={FORM_LABELS.CREDENTIAL_TYPE_PLACEHOLDER}
                    />
                  </SelectTrigger>
                  <SelectContent>
                    {CREDENTIAL_TYPES.map((type) => (
                      <SelectItem key={type} value={type}>
                        {CREDENTIAL_TYPE_LABELS[type]}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Label */}
              <div className="space-y-2">
                <Label htmlFor="credential-label">{FORM_LABELS.LABEL}</Label>
                <Input
                  id="credential-label"
                  value={label}
                  onChange={(e) => setLabel(e.target.value)}
                  placeholder={FORM_LABELS.LABEL_PLACEHOLDER}
                  disabled={creating}
                  maxLength={500}
                />
              </div>

              {/* Issued date (optional) */}
              <div className="space-y-2">
                <Label htmlFor="issued-at">{FORM_LABELS.ISSUED_AT}</Label>
                <Input
                  id="issued-at"
                  type="date"
                  value={issuedAt}
                  onChange={(e) => setIssuedAt(e.target.value)}
                  disabled={creating}
                />
              </div>

              {/* Status notice */}
              {file && fingerprint && (
                <Alert>
                  <Shield className="h-4 w-4" />
                  <AlertDescription>
                    {ISSUE_CREDENTIAL_LABELS.PENDING_NOTICE}
                  </AlertDescription>
                </Alert>
              )}

              {/* Error display */}
              {error && (
                <Alert variant="destructive">
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}
            </div>

            <DialogFooter>
              <Button variant="outline" onClick={handleClose} disabled={creating}>
                Cancel
              </Button>
              <Button onClick={handleSubmit} disabled={!canSubmit}>
                {creating ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    {ISSUE_CREDENTIAL_LABELS.ISSUING_LOADING}
                  </>
                ) : (
                  <>
                    <Award className="mr-2 h-4 w-4" />
                    {ISSUE_CREDENTIAL_LABELS.ISSUE_BUTTON}
                  </>
                )}
              </Button>
            </DialogFooter>
          </>
        )}

        {step === 'success' && (
          <>
            <div className="space-y-4 py-4">
              <div className="flex flex-col items-center text-center">
                <div className="flex h-16 w-16 items-center justify-center rounded-full bg-green-500/10 mb-3">
                  <CheckCircle className="h-8 w-8 text-green-500" />
                </div>
                <h4 className="text-lg font-semibold">
                  {ANCHORING_STATUS_LABELS.SUCCESS_TITLE}
                </h4>
                <p className="text-sm text-muted-foreground mt-1">
                  {ANCHORING_STATUS_LABELS.SUCCESS_PROCESSING}
                </p>
              </div>

              {/* Verification link */}
              {createdAnchor && (
                <div className="rounded-lg border bg-muted/50 p-3 space-y-2">
                  <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                    {ISSUE_CREDENTIAL_LABELS.VERIFICATION_LINK}
                  </p>
                  <div className="flex items-center gap-2">
                    <code className="flex-1 text-xs font-mono truncate">
                      {import.meta.env.VITE_APP_URL || location.origin}
                      {verifyPath(createdAnchor.publicId)}
                    </code>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 px-2 shrink-0"
                      onClick={handleCopyLink}
                      aria-label={ISSUE_CREDENTIAL_LABELS.COPY_LINK_ARIA}
                    >
                      {linkCopied ? (
                        <Check className="h-3.5 w-3.5 text-green-500" />
                      ) : (
                        <Copy className="h-3.5 w-3.5" />
                      )}
                    </Button>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    {ANCHORING_STATUS_LABELS.SHARE_LINK_NOTE}
                  </p>
                </div>
              )}
            </div>

            <DialogFooter>
              <div className="flex w-full gap-2">
                <Button
                  variant="outline"
                  onClick={handleCopyLink}
                  className="flex-1"
                >
                  {linkCopied ? (
                    <Check className="mr-2 h-4 w-4" />
                  ) : (
                    <Copy className="mr-2 h-4 w-4" />
                  )}
                  {ANCHORING_STATUS_LABELS.COPY_LINK}
                </Button>
                {createdAnchor && (
                  <Button
                    variant="outline"
                    onClick={handleViewRecord}
                    className="flex-1"
                  >
                    <ExternalLink className="mr-2 h-4 w-4" />
                    {ANCHORING_STATUS_LABELS.VIEW_RECORD}
                  </Button>
                )}
                <Button onClick={handleIssueAnother}>
                  <Plus className="mr-2 h-4 w-4" />
                  {ANCHORING_STATUS_LABELS.ISSUE_ANOTHER}
                </Button>
              </div>
            </DialogFooter>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}
