-- Migration 0216: Expand jurisdiction_rules seed to ≥100 rules (NCA-01)
-- All ON CONFLICT DO NOTHING so safe to re-run.

INSERT INTO jurisdiction_rules (jurisdiction_code, industry_code, rule_name, required_credential_types, optional_credential_types, regulatory_reference, details) VALUES
('US-FEDERAL', 'education', 'FERPA: Student Education Records Access (NCA-01 expansion)', ARRAY['LICENSE','TRANSCRIPT','CERTIFICATE'], ARRAY['DEGREE'], '20 U.S.C. §1232g; 34 CFR Part 99', '{"annual_notification_required": true, "directory_info_opt_out": true, "parental_consent_under_18": true}'),
('US-FEDERAL', 'education', 'FERPA: Disclosure Log Requirements (NCA-01 expansion)', ARRAY['ATTESTATION'], ARRAY['CERTIFICATE'], '34 CFR §99.32', '{"retention_years": 999, "must_record": ["requester", "legitimate_interest", "disclosed_records"]}'),
('US-FEDERAL', 'education', 'FERPA: Directory Information Public Disclosure (NCA-01 expansion)', ARRAY['ATTESTATION'], ARRAY[]::TEXT[], '34 CFR §99.37', '{"opt_out_window_days": 14, "categories_allowed": ["name","address","phone","email","dates_attended"]}'),
('US-FEDERAL', 'healthcare', 'HIPAA Privacy Rule: PHI Use + Disclosure (NCA-01 expansion)', ARRAY['LICENSE','CERTIFICATE','ATTESTATION'], ARRAY['CONTINUING_EDUCATION'], '45 CFR §§164.502, 164.508', '{"min_necessary_standard": true, "nopp_required": true, "authorization_elements": 6}'),
('US-FEDERAL', 'healthcare', 'HIPAA Security Rule: Administrative Safeguards (NCA-01 expansion)', ARRAY['CERTIFICATE','ATTESTATION'], ARRAY['CONTINUING_EDUCATION'], '45 CFR §164.308', '{"required_addressable_pairs": 18, "workforce_training_required": true, "risk_analysis_required": true}'),
('US-FEDERAL', 'healthcare', 'HIPAA Breach Notification Rule (NCA-01 expansion)', ARRAY['ATTESTATION'], ARRAY['CERTIFICATE'], '45 CFR §§164.400-414', '{"hhs_notice_days": 60, "media_notice_threshold": 500, "individual_notice_days": 60}'),
('US-FEDERAL', 'healthcare', 'HIPAA Business Associate Agreement Requirements (NCA-01 expansion)', ARRAY['ATTESTATION','LICENSE'], ARRAY[]::TEXT[], '45 CFR §164.504(e)', '{"ba_definition": "creates/receives/maintains/transmits PHI", "required_terms": 9}'),
('US-FEDERAL', 'accounting', 'SOX §302: CEO/CFO Certification of Financials (NCA-01 expansion)', ARRAY['LICENSE','ATTESTATION'], ARRAY['DEGREE'], '15 U.S.C. §7241 (SOX §302)', '{"quarterly_certification": true, "annual_certification": true, "personal_liability": true}'),
('US-FEDERAL', 'accounting', 'SOX §404: Internal Control Assessment (NCA-01 expansion)', ARRAY['LICENSE','ATTESTATION','CERTIFICATE'], ARRAY['CONTINUING_EDUCATION'], '15 U.S.C. §7262 (SOX §404)', '{"auditor_attestation_required": true, "icfr_effectiveness_opinion": true}'),
('US-FEDERAL', 'accounting', 'SOX §802: Records Retention (NCA-01 expansion)', ARRAY['ATTESTATION'], ARRAY[]::TEXT[], '18 U.S.C. §§1519, 1520', '{"audit_workpaper_retention_years": 7, "criminal_penalties": true}'),
('KE', 'data_protection', 'Kenya DPA: Data Controller/Processor Registration (NCA-01 expansion)', ARRAY['LICENSE','ATTESTATION'], ARRAY[]::TEXT[], 'Kenya DPA 2019 §§18-24; ODPC Registration', '{"registration_required_above_annual_turnover_ksh": 5000000, "renewal_years": 2}'),
('KE', 'data_protection', 'Kenya DPA: Data Protection Impact Assessment (NCA-01 expansion)', ARRAY['ATTESTATION','CERTIFICATE'], ARRAY['LICENSE'], 'Kenya DPA 2019 §31; ODPC DPIA Guidance', '{"required_for_high_risk": true, "dpo_review_required": true}'),
('KE', 'data_protection', 'Kenya DPA: Data Subject Rights (NCA-01 expansion)', ARRAY['ATTESTATION'], ARRAY['CERTIFICATE'], 'Kenya DPA 2019 §§25-30', '{"response_days": 30, "rights": ["access","rectification","erasure","objection","portability"]}'),
('KE', 'data_protection', 'Kenya DPA: Breach Notification (NCA-01 expansion)', ARRAY['ATTESTATION'], ARRAY[]::TEXT[], 'Kenya DPA 2019 §43', '{"odpc_notification_hours": 72, "individual_notification_if_high_risk": true}'),
('AU', 'data_protection', 'APP 1: Open and Transparent Management (NCA-01 expansion)', ARRAY['ATTESTATION'], ARRAY['CERTIFICATE'], 'Privacy Act 1988 (Cth) Sch 1 APP 1', '{"privacy_policy_required": true, "accessible_form_required": true, "review_periodically": true}'),
('AU', 'data_protection', 'APP 5: Notification of Collection (NCA-01 expansion)', ARRAY['ATTESTATION'], ARRAY[]::TEXT[], 'Privacy Act 1988 (Cth) Sch 1 APP 5', '{"notification_required_at_collection": true, "required_elements": 9}'),
('AU', 'data_protection', 'APP 8: Cross-Border Disclosure (NCA-01 expansion)', ARRAY['ATTESTATION','CERTIFICATE'], ARRAY[]::TEXT[], 'Privacy Act 1988 (Cth) Sch 1 APP 8', '{"reasonable_steps_required": true, "accountability_for_recipient": true}'),
('AU', 'data_protection', 'APP 11: Security of Personal Information (NCA-01 expansion)', ARRAY['CERTIFICATE','ATTESTATION'], ARRAY['CONTINUING_EDUCATION'], 'Privacy Act 1988 (Cth) Sch 1 APP 11', '{"reasonable_steps_to_protect": true, "destruction_or_deidentification_when_no_longer_needed": true}'),
('AU', 'data_protection', 'Notifiable Data Breaches Scheme (NCA-01 expansion)', ARRAY['ATTESTATION'], ARRAY[]::TEXT[], 'Privacy Act 1988 (Cth) Part IIIC', '{"oaic_notification_required": true, "serious_harm_threshold": true, "notification_window_days": 30}')
ON CONFLICT DO NOTHING;;
